### ISSUE TITLE
Segfault with malformed node texture string

### ISSUE THREAD

**Issue by yw05** [minetest/minetest#10949]
##### Minetest version

```
Minetest 5.4.0-dev-375bcd6 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Manjaro Linux (x86_64)
CPU: Intel(R) Core(TM) i7-10510U

GPU model:
OpenGL version:

##### Summary
Registering a node with the texture string `[combine:8x8:0,0=(x^[resize\\:4x4:1,1=y` (note the unbalanced `(`) causes a segfault:
```
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x00005555556fb338 in TextureSource::getTextureAverageColor (this=<optimized out>, name="[combine:8x8:0,0=(x^[resize\\:4x4:1,1=y")
    at ***/minetest/src/client/tile.cpp:2229
2229                    texture->getOriginalSize());
(gdb) bt
#0  0x00005555556fb338 in TextureSource::getTextureAverageColor (this=<optimized out>, name="[combine:8x8:0,0=(x^[resize\\:4x4:1,1=y")
    at ***/minetest/src/client/tile.cpp:2229
#1  0x00005555559e05fc in ContentFeatures::updateTextures (this=0x7fffb1ab7010, tsrc=0x555556a0c5b0, shdsrc=0x555556c0f040, meshmanip=0x555556a18690, client=0x555556cf9620, 
    tsettings=...) at ***/minetest/src/nodedef.cpp:776
#2  0x00005555559e112b in NodeDefManager::updateTextures (this=0x555556c0fb40, gamedef=gamedef@entry=0x555556cf9630, progress_callback=progress_callback@entry=
    0x55555563f3c0 <texture_update_progress(void*, unsigned int, unsigned int)>, progress_callback_args=progress_callback_args@entry=0x7fffffffc630)
    at ***/minetest/src/nodedef.cpp:1457
#3  0x000055555564012f in Client::afterContentReceived (this=0x555556cf9620) at ***/minetest/src/client/client.cpp:1743
#4  0x0000555555692213 in Game::createClient (this=0x7fffffffc870, start_data=...) at ***/minetest/src/client/game.cpp:1340
#5  0x00005555556928fb in Game::startup (this=0x7fffffffc870, kill=<optimized out>, input=<optimized out>, start_data=..., error_message=..., reconnect=<optimized out>, 
    chat_backend=0x7fffffffcd90) at ***/minetest/src/client/game.cpp:1046
#6  0x000055555569bc67 in the_game (kill=kill@entry=0x555555bdc2e0 <porting::g_killed>, input=0x555556aef580, start_data=..., error_message="", chat_backend=..., 
    reconnect_requested=reconnect_requested@entry=0x7fffffffcc34) at ***/minetest/src/client/game.cpp:4245
#7  0x0000555555654fec in ClientLauncher::run (this=this@entry=0x7fffffffd310, start_data=..., cmd_args=...) at ***/minetest/src/client/clientlauncher.cpp:273
#8  0x000055555562fc81 in main (argc=<optimized out>, argv=<optimized out>) at ***/minetest/src/main.cpp:229
```
(Part of the directory name is replaced by `***` for privacy reasons)

##### Steps to reproduce
1. Create a mod with the following string in `init.lua`:
`minetest.register_node(":x",{tiles={"[combine:8x8:0,0=(x^[resize\\:4x4:1,1=y"}})`
Note that `x` and `y` do not have to be actual existing textures.
2. Create a world with the mod enabled.
3. Start the game with the world.

**Comment by sfan5** [comment]
The fix:
```diff
diff --git a/src/client/tile.cpp b/src/client/tile.cpp
index aad956ada..0607512d6 100644
--- a/src/client/tile.cpp
+++ b/src/client/tile.cpp
@@ -2224,9 +2224,13 @@ video::SColor TextureSource::getTextureAverageColor(const std::string &name)
        video::IVideoDriver *driver = RenderingEngine::get_video_driver();
        video::SColor c(0, 0, 0, 0);
        video::ITexture *texture = getTexture(name);
+       if (!texture)
+               return c;
        video::IImage *image = driver->createImage(texture,
                core::position2d<s32>(0, 0),
                texture->getOriginalSize());
+       if (!image)
+               return;
        u32 total = 0;
        u32 tR = 0;
        u32 tG = 0;
```

**Comment by yw05** [comment]
The fix works. Closing.
