### ISSUE TITLE
Minetest 5.2.0.26 won't start on Android 11

### ISSUE THREAD

**Issue by pavlukivan** [minetest/minetest#11369]
Minetest shows the loading bar, then simply crashes after it finishes. Logcat shows the following:
```
insertFileIfNecessary failed
java.lang.IllegalArgumentException: Primary directory Minetest not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
	at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2707)
	at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2372)
	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2982)
	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3521)
	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3237)
	at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:6705)
	at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:6792)
```

**Comment by pavlukivan** [comment]
sorry, i wrongly assumed fdroid would have the latest version...
