### ISSUE TITLE
Revoking permission at MainActivity crashes app

### ISSUE THREAD

**Issue by aper-project** [minetest/minetest#11417]
Hi, there, I found minetestv5.4.1 crashes when storage permission is revoked.
### Minetest version
Minetest 5.4.1
### OS 
Operating system: Android 6.0(API 23)
### summary
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.android.internal.app.IAppOpsCallback.asBinder()' on a null object reference
        at android.os.Parcel.readException(Parcel.java:1626)
        at android.os.Parcel.readException(Parcel.java:1573)
        at com.android.internal.app.IAppOpsService$Stub$Proxy.stopWatchingMode(IAppOpsService.java:432)
        at android.media.SoundPool.release(SoundPool.java:195)
        at android.media.SoundPool.finalize(SoundPool.java:204)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
        at java.lang.Thread.run(Thread.java:818)
### Steps to reproduce
- Step 1
   enter the app from the home screen and allow the storage permission request.
- Step 2
   go to system setting and revoke the storage permission
- Step 3
   go back to the app and it crashes

Here is the video about how I found this crash.

https://user-images.githubusercontent.com/68948244/124443082-f5ee9100-ddaf-11eb-9627-d072c763c107.mp4

@sfan5 
Could you help me review this issue? very thanks !!

**Comment by NathanSalapat** [comment]
This is likely to be expected. Minetest reads the game/mod content from storage, and read/writes the world there as well. If Minetest doesn't have permission to read/write data what is it expected to do?

**Comment by aper-project** [comment]
> This is likely to be expected. Minetest reads the game/mod content from storage, and read/writes the world there as well. If Minetest doesn't have permission to read/write data what is it expected to do?

I think there might be other ways to workaround this, instead of a crash. For example, showing a message to prompt the people for read/write permission, or just request it.

I found that the permission request and checking are already there in `MainActivity`'s `onCreate` ([here](https://github.com/minetest/minetest/blob/master/android/app/src/main/java/net/minetest/minetest/MainActivity.java#L92)), can we just simply place it in other callbacks, like `onResume`?

**Comment by rubenwardy** [comment]
This feels very close to a user error, also the app will rerequest the permission later anyway. From November 2021, we won't be able to request this permission anyway so I'm inclined to not fix this bug
