### ISSUE TITLE
instance hangs on "shutting down stuff" screen with 100% CPU utilization

### ISSUE THREAD

**Issue by mikeraz** [minetest/minetest#1146]
Opening this after discussion with celeron55 on dev IRC.
```
Minetest 0.4.9
Using Irrlicht 1.8.1
Build info: VER=0.4.9 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=0 USE_LUAJIT=0 STATIC_SHAREDIR=/usr/share/minetest

On update to date (Feb 2014) Arch Linux, minetest built on this system.

Stack Trace:
(gdb) backtrace
#0  0x00007f1f3a2db7ac in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007f1f3a2d7477 in _L_lock_531 () from /usr/lib/libpthread.so.0
#2  0x00007f1f3a2d72a0 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#3  0x00000000004832ad in JMutex::Lock (this=this@entry=0x2b256c0)
    at /usr/local/src/minetest-master/src/jthread/pthread/jmutex.cpp:46
#4  0x00000000006968ce in JMutexAutoLock (m=..., this=<synthetic pointer>)
    at /usr/local/src/minetest-master/src/util/../jthread/jmutexautolock.h:37
#5  Server::~Server (this=0x2b255e0, __in_chrg=<optimized out>)
    at /usr/local/src/minetest-master/src/server.cpp:394
#6  0x0000000000696df7 in Server::~Server (this=0x2b255e0, __in_chrg=<optimized out>)
    at /usr/local/src/minetest-master/src/server.cpp:453
#7  0x00000000005a566c in the_game (kill=@0x9afc20: false, random_input=random_input@entry=false,
    input=input@entry=0x2708070, device=device@entry=0x253fd20, font=font@entry=0x26d2b40,
    map_dir=..., playername=..., password=..., address=..., port=port@entry=30000, error_message=...,
    chat_backend=..., gamespec=..., simple_singleplayer_mode=simple_singleplayer_mode@entry=false)
    at /usr/local/src/minetest-master/src/game.cpp:3548
#8  0x0000000000618ede in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/local/src/minetest-master/src/main.cpp:1803

(gdb) thread apply all bt

Thread 5 (Thread 0x7f1f34fda700 (LWP 25375)):
#0  0x00007f1f3a2db0e0 in sem_timedwait () from /usr/lib/libpthread.so.0
#1  0x00000000004834a7 in JSemaphore::Wait (this=this@entry=0x2b258d0, time_ms=time_ms@entry=50)
    at /usr/local/src/minetest-master/src/jthread/pthread/jsemaphore.cpp:70
#2  0x0000000000524df0 in con::ConnectionSendThread::Thread (this=0x2b25808) at /usr/local/src/minetest-master/src/connection.cpp:1239
#3  0x0000000000483547 in JThread::TheThread (param=0x2b25808) at /usr/local/src/minetest-master/src/jthread/pthread/jthread.cpp:203
#4  0x00007f1f3a2d50a2 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f1f38f72d1d in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f1f27fff700 (LWP 25376)):
#0  0x00007f1f38f6bfd3 in select () from /usr/lib/libc.so.6
#1  0x00000000006c4c08 in UDPSocket::WaitData (this=0x2b256e8, timeout_ms=timeout_ms@entry=50) at /usr/local/src/minetest-master/src/socket.cpp:556
#2  0x00000000005283c4 in con::ConnectionReceiveThread::receive (this=this@entry=0x2b25900) at /usr/local/src/minetest-master/src/connection.cpp:2051
#3  0x0000000000528ae0 in con::ConnectionReceiveThread::Thread (this=0x2b25900) at /usr/local/src/minetest-master/src/connection.cpp:1975
#4  0x0000000000483547 in JThread::TheThread (param=0x2b25900) at /usr/local/src/minetest-master/src/jthread/pthread/jthread.cpp:203
#5  0x00007f1f3a2d50a2 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f1f38f72d1d in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f1f35fdc700 (LWP 25377)):
#0  0x00007f1f347d6e15 in ?? ()
#1  0x0000000040b204ac in ?? ()
#2  0x00007f1f0004de7e in ?? ()
#3  0x0000000002cc5eb0 in ?? ()
#4  0x000000000000000a in ?? ()
#5  0x0000000800000001 in ?? ()
#6  0x4168b04040b20378 in ?? ()
#7  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7f1f1c8e2700 (LWP 25412)):
#0  0x00007f1f3a2db7ac in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007f1f3a2d7477 in _L_lock_531 () from /usr/lib/libpthread.so.0
#2  0x00007f1f3a2d72a0 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#3  0x00000000004832ad in JMutex::Lock (this=this@entry=0x2b256c0) at /usr/local/src/minetest-master/src/jthread/pthread/jmutex.cpp:46
#4  0x000000000057d29e in JMutexAutoLock (m=..., this=<synthetic pointer>) at /usr/local/src/minetest-master/src/util/../jthread/jmutexautolock.h:37
#5  EmergeThread::getBlockOrStartGen (this=this@entry=0x2b18540, p=..., b=b@entry=0x7f1f1c8e1b48, data=data@entry=0x7f1f1c8e1bd0, 
    allow_gen=allow_gen@entry=false) at /usr/local/src/minetest-master/src/emerge.cpp:429
#6  0x00000000005809b1 in EmergeThread::Thread (this=0x2b18540) at /usr/local/src/minetest-master/src/emerge.cpp:494
#7  0x0000000000483547 in JThread::TheThread (param=0x2b18540) at /usr/local/src/minetest-master/src/jthread/pthread/jthread.cpp:203
#8  0x00007f1f3a2d50a2 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007f1f38f72d1d in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f1f3d3cd800 (LWP 25362)):
#0  0x00007f1f3a2db7ac in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007f1f3a2d7477 in _L_lock_531 () from /usr/lib/libpthread.so.0
#2  0x00007f1f3a2d72a0 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#3  0x00000000004832ad in JMutex::Lock (this=this@entry=0x2b256c0) at /usr/local/src/minetest-master/src/jthread/pthread/jmutex.cpp:46
#4  0x00000000006968ce in JMutexAutoLock (m=..., this=<synthetic pointer>) at /usr/local/src/minetest-master/src/util/../jthread/jmutexautolock.h:37
#5  Server::~Server (this=0x2b255e0, __in_chrg=<optimized out>) at /usr/local/src/minetest-master/src/server.cpp:394
#6  0x0000000000696df7 in Server::~Server (this=0x2b255e0, __in_chrg=<optimized out>) at /usr/local/src/minetest-master/src/server.cpp:453
#7  0x00000000005a566c in the_game (kill=@0x9afc20: false, random_input=random_input@entry=false, input=input@entry=0x2708070, 
    device=device@entry=0x253fd20, font=font@entry=0x26d2b40, map_dir=..., playername=..., password=..., address=..., port=port@entry=30000, 
    error_message=..., chat_backend=..., gamespec=..., simple_singleplayer_mode=simple_singleplayer_mode@entry=false)
    at /usr/local/src/minetest-master/src/game.cpp:3548
#8  0x0000000000618ede in main (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/minetest-master/src/main.cpp:1803
(gdb) 
```

Can supply world files where this problem occurs.

**Comment by nerzhul** [comment]
hi @mikeraz is this issue still valid ? Will close it on  1st april if it's not valid anymore, nobody report it since months

**Comment by nerzhul** [comment]
Closed
