### ISSUE TITLE
Pixelflood 2 – Segfault Boogaloo: Sending lottapixel.jpg from server segfaults client upon connection

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11628]
##### Minetest version
Minetest commit 719a12eca with irrlichtmt commit 594de99

##### OS / Hardware
Operating system: GNU/Linux
CPU: x64 something

##### Summary
I have upgraded my Pixelflood mod to work with the new code by changing the bytes `0F 0A 0F 0A` in it to `7D 00 7D 00`, giving it an apparent size of 32000×32000 pixels.

```
2021-09-14 22:54:52: ERROR[Main]: Irrlicht: JPEG FATAL ERROR in _tempreadfile: Corrupt JPEG data: bad Huffman code
2021-09-14 22:54:54: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==22014==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x7f8614c45c10 (pc 0x7f888b9b9744 bp 0x7ffcb33a8910 sp 0x7ffcb33a88c8 T22014)
==22014==The signal is caused by a READ memory access.
    #0 0x7f888b9b9743  (/lib/x86_64-linux-gnu/libc.so.6+0x15c743)
    #1 0x1faddbf in irr::video::CColorConverter::convert_A8R8G8B8toA8R8G8B8(void const*, int, void*) (bin/minetest+0x1faddbf)
    #2 0x1fb1d37 in irr::video::CColorConverter::convert_viaFormat(void const*, irr::video::ECOLOR_FORMAT, int, void*, irr::video::ECOLOR_FORMAT) (bin/minetest+0x1fb1d37)
    #3 0x1fb79cb in irr::video::CImage::copyToScaling(void*, unsigned int, unsigned int, irr::video::ECOLOR_FORMAT, unsigned int) (bin/minetest+0x1fb79cb)
    #4 0x1fb7e4f in irr::video::CImage::copyToScaling(irr::video::IImage*) (bin/minetest+0x1fb7e4f)
    #5 0x1f2e64c in irr::video::COpenGLCoreTexture<irr::video::COpenGLDriver>::COpenGLCoreTexture(irr::core::string<char, irr::core::irrAllocator<char> > const&, irr::core::array<irr::video::IImage*, irr::core::irrAllocator<irr::video::IImage*> > const&, irr::video::E_TEXTURE_TYPE, irr::video::COpenGLDriver*) (bin/minetest+0x1f2e64c)
    #6 0x1f0a69f in irr::video::COpenGLDriver::createDeviceDependentTexture(irr::core::string<char, irr::core::irrAllocator<char> > const&, irr::video::IImage*) (bin/minetest+0x1f0a69f)
    #7 0x1eb6ab7 in irr::video::CNullDriver::addTexture(irr::core::string<char, irr::core::irrAllocator<char> > const&, irr::video::IImage*) (bin/minetest+0x1eb6ab7)
    #8 0xfe4054 in TextureSource::generateTexture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (bin/minetest+0xfe4054)
    #9 0xfe344c in TextureSource::getTextureId(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (bin/minetest+0xfe344c)
    #10 0xfe5cb1 in TextureSource::getTexture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int*) (bin/minetest+0xfe5cb1)
    #11 0xff8791 in TextureSource::getTextureAverageColor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (bin/minetest+0xff8791)
    #12 0x1ae9fff in ContentFeatures::updateTextures(ITextureSource*, IShaderSource*, irr::scene::IMeshManipulator*, Client*, TextureSettings const&) (bin/minetest+0x1ae9fff)
    #13 0x1af8bb3 in NodeDefManager::updateTextures(IGameDef*, void*) (bin/minetest+0x1af8bb3)
    #14 0xb97b2e in Client::afterContentReceived() (bin/minetest+0xb97b2e)
    #15 0xd5708c in Game::createClient(GameStartData const&) (bin/minetest+0xd5708c)
    #16 0xd56559 in Game::startup(bool*, InputHandler*, RenderingEngine*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool*, ChatBackend*) (bin/minetest+0xd56559)
    #17 0xd9a1b1 in the_game(bool*, InputHandler*, RenderingEngine*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ChatBackend&, bool*) (bin/minetest+0xd9a1b1)
    #18 0xc2e1cf in ClientLauncher::run(GameStartData&, Settings const&) (bin/minetest+0xc2e1cf)
    #19 0x1a4d78b in main (bin/minetest+0x1a4d78b)
    #20 0x7f888b88109a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #21 0xb06d69 in _start (bin/minetest+0xb06d69)

UndefinedBehaviorSanitizer can not provide additional info.
==22014==ABORTING
# exited 1
```

##### Steps to reproduce
1. Install attached mod on server.
2. Connect to server that runs it.
3. Observe a client segfaulting.

**Comment by erlehmann** [comment]
Forgot to attach the new PIxelflood mod.

**Comment by erlehmann** [comment]
Attached the new pixelflood mod.
