### ISSUE TITLE
Server - Sometimes segmentation fault after "Placing new dungeon"

### ISSUE THREAD

**Issue by UniqueActive** [minetest/minetest#11720]
##### Minetest version
```
Minetest 5.4.1-debug (Linux)
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
**Operating system:** Alpine Linux 3.14 (both machines tested)
**CPU:** Intel Xeon Gold 5220@2.2 GHz (single core VPS, first machine) and Xeon E3 1245@3.3GHz (2nd machine, full 8 cores, full hardware server)
**RAM:** 512MB (first machine) and 32GB (second machine)
First machine has an HDD, second one has an SSD.

##### Summary
The server appears to randomly crash with a "Segmentation fault" when exploring. Only version 0.72 of MineClone2 is installed, no other mods. This was tested on two machines running Alpine Linux 3.14 (see above) with same result.

It was also tested with newest Minetest and MineClone2 directly from git.
The last thing that is logged is always "[mcl_dungeons] Placing new dungeon at [...]", but it does not happen every time that a new dungeon is placed. There are many successful instances of this message without a crash, but sometimes it does crash.

##### Steps to reproduce
1. Launch minetest with MineClone2 installed
2. Explore around as much as possible
3. Suddenly, the server crashes

##### Log/GDB Output:
```
2021-10-23 12:25:37: ACTION[Emerge-0]: [mcl_mapgen_core] Generating chunk (-992,48,-112) ... (-913,127,-33)
2021-10-23 12:25:37: ACTION[Emerge-0]: [mcl_dungeons] Placing new dungeon at (-843,-38,-101)
                                                                                                                                                             
Thread 5 "Emerge-0" received signal SIGSEGV, Segmentation fault.              
[Switching to LWP 14324]                                                      
0x000055555590d43e in ServerMap::updateVManip (this=0x7ffff763f8c0, pos=...) at /home/admin/src/minetest/src/map.cpp:1568
1568            vm->m_data[idx] = getNode(pos);                     
#0  0x000055555590d43e in ServerMap::updateVManip (this=0x7ffff763f8c0, pos=...) at /home/admin/src/minetest/src/map.cpp:1568
#1  0x000055555599e931 in ServerEnvironment::swapNode (this=0x7ffff461c030, p=..., n=...) at /home/admin/src/minetest/src/serverenvironment.cpp:1063
#2  0x00005555557735b7 in ModApiEnvMod::l_swap_node (L=0x7ffff7595380) at /home/admin/src/minetest/src/script/lua_api/l_env.cpp:344
#3  0x000055555574691f in script_exception_wrapper (L=0x7ffff7595380, f=0x5555557734ec <ModApiEnvMod::l_swap_node(lua_State*)>)
    at /home/admin/src/minetest/src/script/common/c_internal.cpp:38                                                                                          
#4  0x00007ffff7dc7fea in ?? () from /usr/lib/libluajit-5.1.so.2
#5  0x00007ffff7e08332 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
#6  0x0000555555754355 in ScriptApiEnv::on_emerge_area_completion (this=0x7ffff7730550, blockpos=..., action=2, state=0x7ffff141c4e0)
    at /home/admin/src/minetest/src/script/cpp_api/s_env.cpp:250
#7  0x000055555577310d in LuaEmergeAreaCallback (blockpos=..., action=EMERGE_FROM_MEMORY, param=0x7ffff141c4e0)
    at /home/admin/src/minetest/src/script/lua_api/l_env.cpp:257
#8  0x00005555558bd08b in EmergeThread::runCompletionCallbacks (pos=..., action=EMERGE_FROM_MEMORY, callbacks=...)
    at /home/admin/src/minetest/src/emerge.cpp:554                  
#9  0x00005555558bddc7 in EmergeThread::run (this=0x7ffff77754f0) at /home/admin/src/minetest/src/emerge.cpp:699
#10 0x00005555557d68d7 in Thread::threadProc (thr=0x7ffff77754f0) at /home/admin/src/minetest/src/threading/thread.cpp:188
#11 0x00005555557d74de in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x7ffff19d7b30: 0x5555557d6868 <Thread::threadProc(Thread*)>)
    at /usr/include/c++/10.3.1/bits/invoke.h:60          
#12 0x00005555557d7445 in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x7ffff19d7b30: 0x5555557d6868 <Thread::threadProc(Thread*)>)
    at /usr/include/c++/10.3.1/bits/invoke.h:95              
#13 0x00005555557d73b5 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x7ffff19d7b28)
    at /usr/include/c++/10.3.1/thread:264                      
#14 0x00005555557d736e in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x7ffff19d7b28)
    at /usr/include/c++/10.3.1/thread:271                      
#15 0x00005555557d7352 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x7ffff19d7b20)            
    at /usr/include/c++/10.3.1/thread:215                                                                                                                    
#16 0x00007ffff7c1d713 in ?? () from /usr/lib/libstdc++.so.6   
#17 0x00007ffff7fba1bb in ?? () from /lib/ld-musl-x86_64.so.1  
#18 0x0000000000000000 in ?? ()
```

Any pointers about possible causes or solutions are much appreciated!

**Comment by UniqueActive** [comment]
Hey, just wanted to let you know that we have not seen any crash since applying your patch, thank you very much for looking into it! :)
