### ISSUE TITLE
Raspberry pi Segmentation fault

### ISSUE THREAD

**Issue by DragonFire125** [minetest/minetest#12594]
##### Minetest version
```
Minetest 5.5.1 (Linux)
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
Raspberry Pi 4 Model B 2GB
Operating system:Raspberry Pi OS 64 bit Bullseye 
CPU:BCM 2711 aarch64, Arm64 1.5GHZ 4X

##### Summary
minetestserver on Raspberry pi with a some mods 20+ no specific mod  
i will get the Segmentation fault error and crash after the runs the server for a bit of time or on startup some times
it crashes more often the more mods i have

##### Steps to reproduce
run minetestserver on raspberry pi with many mods 

##### notes 
i ran gdb -q -ex 'set confirm off' -ex 'r' -ex 'bt' -ex 'quit' --args ./minetestserver ... and got
`Reading symbols from ./minetestserver...
(No debugging symbols found in ./minetestserver)
Starting program: /home/pi/minetest-5.5.1/bin/minetestserver ...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff6526d80 (LWP 33547)]
[New Thread 0x7ff5d25d80 (LWP 33548)]

Thread 1 "minetestserver" received signal SIGSEGV, Segmentation fault.
0x0000007ff52e55cc in ?? ()
#0  0x0000007ff52e55cc in ?? ()
#1  0x0000000000000002 in ?? ()`

**Comment by sfan5** [comment]
Try recompiling Minetest with LuaJIT from git first to see if that fixes the crashes.
