### ISSUE TITLE
Clients < 5.6 crash/hang when sent new-style particles

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#12657]
The changes/upgrades to Minetest's particle system do NOT degrade gracefully on older clients. For example, sending this to a < 5.6 client will cause it to hang (but the server will not crash):

```
minetest.add_particlespawner({
  amount = 160,
  time = time,
  minpos = {x=pos.x-xd, y=pos.y-0, z=pos.z-zd},
  maxpos = {x=pos.x+xd, y=pos.y+2, z=pos.z+zd},
  minvel = {x=0, y=-1, z=0},
  maxvel = {x=0, y=1, z=0},
  minacc = {x=0, y=-1, z=0},
  maxacc = {x=0, y=1, z=0},
  minexptime = 1.0,
  maxexptime = 2.5,
  minsize = 1.0,
  maxsize = 1.0,
  collisiondetection = true,
  collision_removal = true,
  vertical = false,
  
  texture = "nether_particle_anim1.png",
  animation = {
	  type = "vertical_frames",
	  aspect_w = 7,
	  aspect_h = 7,
	  length = -1,
  },
  
  glow = 14,
})
```

I tested and the issue is specifically around the `length = -1` line. If you give a positive value as you would normally, the client does not crash. ~~However! Neither does the particle run through its animation frames.~~

EDIT: Last sentence is in error, I was simply supplying too large an animation value (the documentation doesn't make it explicit that this is time in seconds, rather than the number of frames, and I forgot about that ...)

**Comment by SmallJoker** [comment]
Full testing code
```lua

minetest.register_chatcommand("p", {
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		local pos = vector.round(player:get_pos())
		local xd, zd, time = 1, 1, 10

		minetest.add_particlespawner({
			amount = 160,
			time = time,
			minpos = {x=pos.x-xd, y=pos.y-0, z=pos.z-zd},
			maxpos = {x=pos.x+xd, y=pos.y+2, z=pos.z+zd},
			minvel = {x=0, y=-1, z=0},
			maxvel = {x=0, y=1, z=0},
			minacc = {x=0, y=-1, z=0},
			maxacc = {x=0, y=1, z=0},
			minexptime = 1.0,
			maxexptime = 2.5,
			minsize = 1.0,
			maxsize = 1.0,
			collisiondetection = true,
			collision_removal = true,
			vertical = false,
  
			texture = "default_furnace_front_active.png",
			animation = {
				type = "vertical_frames",
				aspect_w = 7,
				aspect_h = 7,
				length = -1,
			},
  
			glow = 14,
		})
	end
})
```

backtrace
```C++
Thread 1 "minetest_auth_m" received signal SIGINT, Interrupt.
0x0000555555732892 in Particle::step(float) ()
(gdb) bt
#0  0x0000555555732892 in Particle::step(float) ()
#1  0x0000555555732c2e in ParticleManager::stepParticles(float) ()
#2  0x0000555555736387 in ParticleManager::step(float) ()
#3  0x00005555556d4f13 in Game::updateFrame(ProfilerGraph*, RunStats*, float, CameraOrientation const&) ()
#4  0x00005555556d906d in Game::run() ()
#5  0x00005555556d9cc4 in the_game(bool*, InputHandler*, RenderingEngine*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ChatBackend&, bool*)
    ()
#6  0x000055555567985c in ClientLauncher::run(GameStartData&, Settings const&) ()
#7  0x000055555564a685 in main ()
```

**Comment by rubenwardy** [comment]
> This is not a regression. The bug already existed before the advanced particle animations.

If this is true, then this issue should about this bug rather than a new-style particle protocol issue
