### ISSUE TITLE
`read_schematic` causes out-of-bounds memory access

### ISSUE THREAD

**Issue by AsumFace** [minetest/minetest#12908]
##### Minetest version

Tested on 
```
5.6.0
recent master (b8292319924994352d56d6111faa73fe315d149a)
```

##### OS / Hardware

Operating system:
Fedora 36
CPU:
AMD EPYC 7702P
Intel i7 4770k

##### Summary

Trying to read a schematic a second time causes a segfault in release builds or, if you're lucky, an assertion failure in debug builds:
```
/usr/include/c++/12/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; const_reference = const std::__cxx11::basic_string<char>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed. 
```
(aka "you indexed a zero-size `Vector`")

The problem appears to be that the schematic cache is not operating correctly. The second time the function is invoked, the node-name list in the retrieved `Schematic` object is empty, causing a memory violation later when the `names` vector is indexed at https://github.com/minetest/minetest/blob/b8292319924994352d56d6111faa73fe315d149a/src/script/lua_api/l_mapgen.cpp#L1748

##### Steps to reproduce

Use `read_schematic` on the same schematic twice. I have tested this with MTS schematics only.

```lua
local path = minetest.get_modpath("default") .. "/schematics/aspen_tree.mts" 
minetest.read_schematic(path, {}) 
minetest.read_schematic(path, {})
```
<details>
<summary>Stack Trace</summary>

```
#0  0x00007fcbb4d41c0c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007fcbb4cf1986 in raise () from /lib64/libc.so.6
#2  0x00007fcbb4cdb7f4 in abort () from /lib64/libc.so.6
#3  0x00007fcbb508cdd0 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () from /lib64/libstdc++.so.6
#4  0x00000000004b2ef2 in std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::operator[] (
    this=0x23f65f0, __n=126) at /usr/include/c++/12/bits/stl_vector.h:1142
#5  0x000000000056ba1a in ModApiMapgen::l_read_schematic (L=0x7fcbb3097380) at /home/minetest/minetest/src/script/lua_api/l_mapgen.cpp:1748
#6  0x000000000051e562 in script_exception_wrapper (L=0x7fcbb3097380, f=0x56b620 <ModApiMapgen::l_read_schematic(lua_State*)>) at /home/minetest/minetest/src/script/common/c_internal.cpp:40
#7  0x00007fcbb54feaf0 in lj_BC_FUNCCW () from /lib64/libluajit-5.1.so.2
#8  0x00007fcbb55112f2 in lua_pcall () from /lib64/libluajit-5.1.so.2
#9  0x000000000052e802 in ScriptApiBase::runCallbacksRaw (this=0x238e118, nargs=2, mode=RUN_CALLBACKS_MODE_OR_SC, fxn=0x7d57b2 "on_chat_message") at /home/minetest/minetest/src/script/cpp_api/s_base.cpp:333
#10 0x00000000005475e5 in ScriptApiServer::on_chat_message (this=0x238df70, name="Diaeresis", 
    message="//lua local path = minetest.get_modpath(\"default\") .. \"/schematics/aspen_tree.mts\" minetest.read_schematic(path, {}) minetest.read_schematic(path, {})") at /home/minetest/minetest/src/script/cpp_api/s_server.cpp:152
#11 0x00000000006e9947 in Server::handleChat (this=0x7fff7a4187f0, name="Diaeresis", 
    wmessage=L"//lua local path = minetest.get_modpath(\"default\") .. \"/schematics/aspen_tree.mts\" minetest.read_schematic(path, {}) minetest.read_schematic(path, {})", check_shout_priv=true, player=0x7fcb8004c4c0)
    at /home/minetest/minetest/src/server.cpp:3055
#12 0x00000000004f0dc5 in Server::handleCommand_ChatMessage (this=0x7fff7a4187f0, pkt=0x7fcb9e222a10) at /home/minetest/minetest/src/network/serverpackethandler.cpp:768
#13 0x00000000006f2528 in Server::handleCommand (this=0x7fff7a4187f0, pkt=0x7fcb9e222a10) at /home/minetest/minetest/src/server.cpp:1152
#14 0x00000000006de62a in Server::ProcessData (this=0x7fff7a4187f0, pkt=0x7fcb9e222a10) at /home/minetest/minetest/src/server.cpp:1227
#15 0x00000000006dd842 in Server::Receive (this=0x7fff7a4187f0) at /home/minetest/minetest/src/server.cpp:1056
#16 0x00000000006d6637 in ServerThread::run (this=0x22861c0) at /home/minetest/minetest/src/server.cpp:122
#17 0x00000000005b7ae3 in Thread::threadProc (thr=0x22861c0) at /home/minetest/minetest/src/threading/thread.cpp:188
#18 0x00000000005b868a in std::__invoke_impl<void, void (*)(Thread*), Thread*> (__f=@0x6d50070: 0x5b7a76 <Thread::threadProc(Thread*)>) at /usr/include/c++/12/bits/invoke.h:61
#19 0x00000000005b860d in std::__invoke<void (*)(Thread*), Thread*> (__fn=@0x6d50070: 0x5b7a76 <Thread::threadProc(Thread*)>) at /usr/include/c++/12/bits/invoke.h:96
#20 0x00000000005b857d in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::_M_invoke<0ul, 1ul> (this=0x6d50068) at /usr/include/c++/12/bits/std_thread.h:252
#21 0x00000000005b8536 in std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> >::operator() (this=0x6d50068) at /usr/include/c++/12/bits/std_thread.h:259
#22 0x00000000005b851a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*), Thread*> > >::_M_run (this=0x6d50060) at /usr/include/c++/12/bits/std_thread.h:210
#23 0x00007fcbb5090b03 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#24 0x00007fcbb4d3fded in start_thread () from /lib64/libc.so.6
#25 0x00007fcbb4dc5370 in clone3 () from /lib64/libc.so.6
```

</details>

**Comment by TurkeyMcMac** [comment]
Are you reading the schematic after mod load time perchance?
