### ISSUE TITLE
Segmentation fault when entity with on_detach_child is removed

### ISSUE THREAD

**Issue by doxygen-spammer** [minetest/minetest#12986]
##### Minetest version
```
Minetest 5.7.0-dev-1a045da0d (Linux)
Using Irrlicht 1.9.0mt9
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

##### OS / Hardware
Operating System: KDE neon 5.26
Kernel Version: 5.15.0-53-generic (64-bit)
Processors: 4 × Intel® Core™ i5-4300U CPU @ 1.90GHz
Memory: 7.5 GiB of RAM

##### Summary
The engine crashes with certain combinations of entity callbacks.
I don’t understand which conditions exactly there are, but I have an example mod that triggers this crash.

To my opinion the mod is perfectly valid, and it is actually an engine bug.

Backtrace with gdb:

```gdb
2022-11-23 13:28:27: ACTION[Server]: doxydoxy2 right-clicks object 1: player doxydoxy
2022-11-23 13:28:27: ACTION[Server]: doxydoxy2 right-clicks object 1: player doxydoxy
2022-11-23 13:28:27: [Server]: Removing dummy

Thread 16 "Server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd3fff700 (LWP 32498)]
0x0000555555a43804 in UnitSAO::clearChildAttachments() ()
(gdb) backtrace
#0  0x0000555555a43804 in UnitSAO::clearChildAttachments() ()
#1  0x0000555555a06570 in ObjectRef::l_remove(lua_State*) ()
#2  0x000055555599caaa in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#3  0x00007ffff7b08017 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#4  0x00007ffff7b564a4 in lua_pcall () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x00005555559a7125 in ScriptApiBase::runCallbacksRaw(int, RunCallbacksMode, char const*) ()
#6  0x00005555559b961b in ScriptApiPlayer::on_rightclickplayer(ServerActiveObject*, ServerActiveObject*) ()
#7  0x000055555598327c in Server::handleCommand_Interact(NetworkPacket*) ()
#8  0x0000555555c43e3d in Server::ProcessData(NetworkPacket*) ()
#9  0x0000555555c44020 in Server::Receive() ()
#10 0x0000555555c58c6a in ServerThread::run() ()
#11 0x0000555555a498e7 in Thread::threadProc(Thread*) ()
#12 0x00007ffff759bde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff7340609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007ffff7265133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

###### Doxytheories :D

* The attachment chain is: player → object → player
* Now we remove the object: player → ~~object~~ → player
* The object will clear its children’s attachments now: player → ~~object~~ ⇢ player
* The object, already removed, calls its own `on_detach_child`: player → ~~object~~:on_detach_child() ↶ player
* This callback calls `self.object:remove()`.
* Segmentation fault, because the engine has already deleted the “actual” object.

##### Steps to reproduce
Use this as a server mod init.lua file.
Start a multiplayer game (from the minetest client with “Host Server” for example).
Join the multiplayer game with a second client.
From the second client, rightclick the admin several times.
The server crashes on an even-th rightclick, which is when `set_detach` is called.
In my case, there is a 10% chance for this crash, but it is reliable.

```lua
-- SPDX-FileCopyrightText: 2022 David Hurka <doxydoxy@mailbox.org>
--
-- SPDX-License-Identifier: GPL-2.0-or-later OR CC0-1.0 OR MIT

local V = vector.new;

local function make_immortal(self)
    self.object:set_armor_groups({ immortal = 1 });
end

local function disappear(self)
    self.object:remove();
end

minetest.register_entity("crash_test:dummy", {
        physical = false;
        collisionbox = { 0, 0, 0, 0, 0, 0 };
        visual = "sprite";
        texture = "default_sand.png";
        on_activate = make_immortal;
        on_detach = disappear;
        on_detach_child = disappear;
        on_deactivate = function()
            minetest.debug("Removing dummy");
        end;
    });

local function attach_player(player, clicker)
    local attachment_dummy = minetest.add_entity(player:get_pos(), "crash_test:dummy");

    attachment_dummy:set_attach(player, "", V(-5, 8, 2), V(0, 90, 0), --[[ forced_visible ]] true);

    clicker:set_attach(attachment_dummy, "", V(0, -2, 0), V(0, 0, 0), --[[ forced_visible ]] true);
end

local function on_rightclickplayer_handler(player, clicker)
    if clicker:get_attach() then
        local children = player:get_children();
        minetest.debug("Removing is successful from Lua side.");
        children[1]:remove();
    else
        attach_player(player, clicker);
    end
end

minetest.register_on_rightclickplayer(on_rightclickplayer_handler);
```

##### Workaround

These wrappers around the remove method seem to avoid the crash.

```lua
-- SPDX-FileCopyrightText: 2022 David Hurka <doxydoxy@mailbox.org>
--
-- SPDX-License-Identifier: GPL-2.0-or-later OR CC0-1.0 OR MIT

--! Workaround for Minetest engine bug #12986.
--! This function must be called @e always instead of the remove() method,
--! if you are working with objects as attachment dummies in certain ways.
--!
--! Calls remove() on the ObjectRef @p object.
--! Uses the luaentity to prevent secondary calls to remove().
--!
--! Usable as entity callback handler, by accepting a luaentity as @p object.
function util.remove_object(object)
    -- Also accept entities.
    local o = object.object or object;

    local l = o:get_luaentity();
    if not l then
        -- I must admit that I don’t really understand the relation of object vs. luaentity.
        minetest.log("error", "Trying to prevent engine crash #12986, but the object has no luaentity.");
        return;
    end

    if not l.i_am_removed then
        l.i_am_removed = true;
        o:remove();
    end
end

--! Callback handler for entities, that makes the entity disappear immediately.
--!
--! Tries to avoid Minetest bug #12968.
function util.entity_disappear(entity)
    util.remove_object(entity.object);
end
```

**Comment by doxygen-spammer** [comment]
Wow, you are fast! :)

I think I found a working workaround, after adding some debug lines everywhere.
Minetest seems to crash after returning from all luaentity callbacks, but only when the object was accessed during these callbacks.

Adding it to the issue description.
