### ISSUE TITLE
Malformed png texmod segfaults the client

### ISSUE THREAD

**Issue by Kimapr** [minetest/minetest#13268]
##### Minetest version

```
5.6.1, 5.7.0-dev-something
```

##### OS / Hardware

Operating system: Debian Unstable, Android 11
CPU: AMD Ryzen 5 3500U, something ARM

##### Summary

:skull: 

##### Steps to reproduce

```lua
minetest.register_chatcommand("killme",{
	func=function(name,param)
		minetest.show_formspec(name,"skull","image[0,0;0,0;\\[png:]")
	end
})
minetest.register_node(":segnode",{
  tiles={"[png:"}
})
minetest.register_craftitem(":segitem",{
  inventory_image="[png:"
})
```
1. run the command/get one of the `seg`items

Segmentation fault

**Comment by rubenwardy** [comment]
Backtrace:

```
#0  TextureSource::generateImagePart (this=0x5555569a8f90, part_of_name="[png:", baseimg=@0x7fffffffb680: 0x0, source_image_names=std::set with 0 elements) at /home/ruben/dev/minetest/src/client/tile.cpp:1876
        dim = {Width = 4294948224, Height = 32767}
        png = ""
        device = 0x5555567537b0
        vd = 0x5555567860b0
        memfile = 0x55555bb325a0
        pngimg = 0x0
        sf = {str = "[png:", pos = 5}
        fs = 0x5555564ceef0
        escape = 92 '\\'
        driver = 0x5555567860b0
        __PRETTY_FUNCTION__ = "bool TextureSource::generateImagePart(std::string, irr::video::IImage*&, std::set<std::__cxx11::basic_string<char> >&)"
#1  0x0000555555919ae3 in TextureSource::generateImage (this=0x5555569a8f90, name="[png:", source_image_names=std::set with 0 elements) at /home/ruben/dev/minetest/src/client/tile.cpp:1043
        separator = 94 '^'
        escape = 92 '\\'
        paren_open = 40 '('
        paren_close = 41 ')'
        last_separator_pos = -1
        paren_bal = 0 '\000'
        baseimg = 0x0
        last_part_of_name = "[png:"
#2  0x000055555591719e in TextureSource::generateTexture (this=0x5555569a8f90, name="[png:") at /home/ruben/dev/minetest/src/client/tile.cpp:616
        driver = 0x5555567860b0
        __PRETTY_FUNCTION__ = "irr::u32 TextureSource::generateTexture(const std::string&)"
        source_image_names = std::set with 0 elements
        img = 0x55555579c11f <std::operator< <char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+35>
        tex = 0x5555569a9040
        lock = {_M_device = 0x5555569a9048, _M_owns = 144}
        id = 597626063
        ti = ...
#3  0x0000555555916d60 in TextureSource::getTextureId (this=0x5555569a8f90, name="[png:") at /home/ruben/dev/minetest/src/client/tile.cpp:506
        result_queue = {<MutexedQueue<GetResult<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::thread::id, unsigned char> >> = {m_queue = std::deque with -9 elements, 
            m_mutex = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
                  __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}, m_signal = {semaphore = {__size = '\000' <repeats 31 times>, __align = 0}}}, <No data fields>}
#4  0x000055555591767a in TextureSource::getTexture (this=0x5555569a8f90, name="[png:", id=0x0) at /home/ruben/dev/minetest/src/client/tile.cpp:671
        actual_id = 0
#5  0x000055555599a739 in GUIFormSpecMenu::parseImage (this=0x55555bbcd3f0, data=0x7fffffffc060, element="0,0;0,0;\\[png:") at /home/ruben/dev/minetest/src/gui/guiFormSpecMenu.cpp:769
        parts = std::vector of length 3, capacity 4 = {"0,0", "0,0", "\\[png:"}
        offset = 1
        v_pos = std::vector of length 2, capacity 2 = {"0", "0"}
        v_geom = std::vector of length 2, capacity 2 = {"0", "0"}
        name = "[png:"
        texture = 0x2
        pos = {X = -18048, Y = 32767}
        geom = {X = 1433851800, Y = 21845}
        spec = {fname=..., fid = -17712, send = 255, ftype = 1534954720, is_exit = 85, priority = -17696, rect = {UpperLeftCorner = {X = 32767, Y = 1433862235}, LowerRightCorner = {X = 21845, Y = -17657}}, fcursor_icon = 32767, sound = ""}
        rect = {UpperLeftCorner = {X = 2, Y = 0}, LowerRightCorner = {X = 1534730784, Y = 21845}}
        middle = {UpperLeftCorner = {X = 0, Y = 0}, LowerRightCorner = {X = 0, Y = 0}}
        e = 0x555555770127 <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long)+71>
        style = {}}, state_map = (StyleSpec::STATE_HOVERED | StyleSpec::NUM_STATES)}
#6  0x00005555559ad901 in GUIFormSpecMenu::parseElement (this=0x55555bbcd3f0, data=0x7fffffffc060, element="image[0,0;0,0;\\[png:") at /home/ruben/dev/minetest/src/gui/guiFormSpecMenu.cpp:2858
        pos = 5
        type = "image"
        description = "0,0;0,0;\\[png:"
```

**Comment by Kimapr** [comment]
Also works with node tiles and inventory images
```lua
minetest.register_node(":segnode",{
  tiles={"[png:"}
})
minetest.register_craftitem(":segitem",{
  inventory_image="[png:"
}
```
