### ISSUE TITLE
minetest crashes when opening chat with very small window sizes

### ISSUE THREAD

**Issue by Niklp09** [minetest/minetest#13298]
##### Minetest version
```
5.7.0-dev-debug-1f0d04237
```

##### OS / Hardware

Operating system: Manjaro (gcc 12.2.1)
CPU: Intel core i5

GPU model: nvidia
OpenGL version: 4.6

##### Summary
minetest crashes when opening chat with very small window sizes. (100x30 pixels on a full hd screen)
![Screenshot_20230307_211519](https://user-images.githubusercontent.com/89982526/223542208-88f8e3b6-6db1-4214-8120-80a8ba454aca.png)
<details>

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 2) > this->size() (which is 1)

Thread 1 "minetest" received signal SIGABRT, Aborted.
0x00007ffff6ea08ec in ?? () from /usr/lib/libc.so.6
#0  0x00007ffff6ea08ec in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff6e51ea8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff6e3b53d in abort () from /usr/lib/libc.so.6
#3  0x00007ffff709a833 in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff70a6d0c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff70a6d79 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff70a6fdd in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff722a148 <typeinfo for std::out_of_range>, dest=0x7ffff70be720 <std::out_of_range::~out_of_range()>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007ffff709d55b in std::__throw_out_of_range_fmt (__fmt=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/functexcept.cc:101
#8  0x00005555557c9c57 in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_check (this=0x7fffffffd350, __pos=2, __s=0x555555f96e52 "basic_string::substr") at /usr/include/c++/12.2.1/bits/basic_string.h:382
#9  0x000055555598b3d0 in std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::substr (this=0x7fffffffd350, __pos=2, __n=0) at /usr/include/c++/12.2.1/bits/basic_string.h:3124
#10 0x0000555555c7ba27 in ChatPrompt::getVisiblePortion[abi:cxx11]() const (this=0x7fffffffd330) at /home/nik/minetest/src/chat.cpp:673
#11 0x0000555555989518 in GUIChatConsole::drawPrompt (this=0x555577123ff0) at /home/nik/minetest/src/gui/guiChatConsole.cpp:357
#12 0x0000555555988ba7 in GUIChatConsole::draw (this=0x555577123ff0) at /home/nik/minetest/src/gui/guiChatConsole.cpp:207
#13 0x000055555597dbce in irr::gui::IGUIElement::draw (this=0x555556d67b68) at /home/nik/minetest/lib/irrlichtmt/include/IGUIElement.h:337
#14 0x0000555555e46cc9 in irr::gui::CGUIEnvironment::drawAll (this=0x555556d67b60, useScreenSize=true) at /home/nik/minetest/lib/irrlichtmt/source/Irrlicht/CGUIEnvironment.cpp:187
#15 0x00005555558d796c in DrawHUD::run (this=0x55557762fa20, context=...) at /home/nik/minetest/src/client/render/plain.cpp:64
#16 0x00005555558d31f4 in RenderPipeline::run (this=0x55557713e770, context=...) at /home/nik/minetest/src/client/render/pipeline.cpp:284
#17 0x00005555558cd2ba in RenderingCore::draw (this=0x5555771413e0, _skycolor=..., _show_hud=true, _show_minimap=false, _draw_wield_tool=true, _draw_crosshair=true) at /home/nik/minetest/src/client/render/core.cpp:60
#18 0x00005555558e043d in RenderingEngine::draw_scene (this=0x5555564b8b90, skycolor=..., show_hud=true, show_minimap=false, draw_wield_tool=true, draw_crosshair=true) at /home/nik/minetest/src/client/renderingengine.cpp:555
#19 0x000055555583d769 in Game::updateFrame (this=0x7fffffffcd60, graph=0x7fffffffcb40, stats=0x7fffffffcb00, dtime=0.0133159999, cam=...) at /home/nik/minetest/src/client/game.cpp:4160
#20 0x000055555582cb8b in Game::run (this=0x7fffffffcd60) at /home/nik/minetest/src/client/game.cpp:1276
#21 0x00005555558415cd in the_game (kill=0x55555644f7a0 <porting::g_killed>, input=0x555556d78970, rendering_engine=0x5555564b8b90, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7fffffffd0bc) at /home/nik/minetest/src/client/game.cpp:4512
#22 0x00005555557c2b05 in ClientLauncher::run (this=0x7fffffffd400, start_data=..., cmd_args=...) at /home/nik/minetest/src/client/clientlauncher.cpp:264
#23 0x0000555555d0fce2 in main (argc=1, argv=0x7fffffffd8a8) at /home/nik/minetest/src/main.cpp:262
```

</details>

##### Steps to reproduce
1. Set `screen_w = 100, screen_h = 30` in your minetest.conf
2. Join a server
3. Open the chat

**Comment by srifqi** [comment]
I can confirm this (Windows 10). It occurs when the window's height is less than 220 px (screen size: 1920 px × 1080 px).

<details>
<summary>Stack backtrace</summary>

```
minetest.exe!std::_String_val<std::_Simple_types<wchar_t>>::_Xran() Line 2305
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2305)
minetest.exe!std::_String_val<std::_Simple_types<wchar_t>>::_Check_offset(const unsigned __int64 _Off) Line 2294
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2294)
minetest.exe!std::wstring::assign(const std::wstring & _Right, const unsigned __int64 _Roff, unsigned __int64 _Count) Line 3189
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(3189)
minetest.exe!std::wstring::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>(const std::wstring & _Right, const unsigned __int64 _Roff, const unsigned __int64 _Count, const std::allocator<wchar_t> & _Al) Line 2460
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(2460)
minetest.exe!std::wstring::substr(const unsigned __int64 _Off, const unsigned __int64 _Count) Line 4333
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(4333)
minetest.exe!ChatPrompt::getVisiblePortion() Line 673
	at C:\git\minetest\src\chat.cpp(673)
minetest.exe!GUIChatConsole::drawPrompt() Line 357
	at C:\git\minetest\src\gui\guiChatConsole.cpp(357)
minetest.exe!GUIChatConsole::draw() Line 210
	at C:\git\minetest\src\gui\guiChatConsole.cpp(210)
minetest.exe!irr::gui::IGUIElement::draw() Line 337
	at C:\git\minetest\lib\irrlichtmt\include\IGUIElement.h(337)
minetest.exe!irr::gui::CGUIEnvironment::drawAll(bool useScreenSize) Line 188
	at C:\git\minetest\lib\irrlichtmt\source\Irrlicht\CGUIEnvironment.cpp(188)
minetest.exe!DrawHUD::run(PipelineContext & context) Line 65
	at C:\git\minetest\src\client\render\plain.cpp(65)
minetest.exe!RenderPipeline::run(PipelineContext & context) Line 284
	at C:\git\minetest\src\client\render\pipeline.cpp(284)
minetest.exe!RenderingCore::draw(irr::video::SColor _skycolor, bool _show_hud, bool _show_minimap, bool _draw_wield_tool, bool _draw_crosshair) Line 61
	at C:\git\minetest\src\client\render\core.cpp(61)
minetest.exe!RenderingEngine::draw_scene(irr::video::SColor skycolor, bool show_hud, bool show_minimap, bool draw_wield_tool, bool draw_crosshair) Line 556
	at C:\git\minetest\src\client\renderingengine.cpp(556)
minetest.exe!Game::updateFrame(ProfilerGraph * graph, RunStats * stats, float dtime, const CameraOrientation & cam) Line 4166
	at C:\git\minetest\src\client\game.cpp(4166)
minetest.exe!Game::run() Line 1277
	at C:\git\minetest\src\client\game.cpp(1277)
minetest.exe!the_game(bool * kill, InputHandler * input, RenderingEngine * rendering_engine, const GameStartData & start_data, std::string & error_message, ChatBackend & chat_backend, bool * reconnect_requested) Line 4512
	at C:\git\minetest\src\client\game.cpp(4512)
minetest.exe!ClientLauncher::run(GameStartData & start_data, const Settings & cmd_args) Line 264
	at C:\git\minetest\src\client\clientlauncher.cpp(264)
minetest.exe!main(int argc, char * * argv) Line 262
	at C:\git\minetest\src\main.cpp(262)
[External Code]
```
</details>
