### ISSUE TITLE
Crash after exiting game session: MinGW thread_local problem

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14140]
happening since 47e557b96ad4b9f053cf35150b2f46fe623b4dc7

backtrace looks like this:
```
Thread 31 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 3856.0x1e98]
0x00007ff79cca5c32 in LogStream::~LogStream() ()
(gdb) bt
#0  0x00007ff79cca5c32 in LogStream::~LogStream() ()
#1  0x00007ffcd274c099 in ?? ()
#2  0x00007ffd0ab4a050 in ?? ()
#3  0x00007ffd24d7f05b in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x000000000cff2240 in ?? ()
#6  0x0000000000000001 in ?? ()
#7  0x000000000cff2240 in ?? ()
#8  0x00007ffd0ab4a050 in ?? ()
#9  0x00007ffd0ab44a40 in ?? ()
#10 0x000000000c79c200 in ?? ()
#11 0x00007ffd00000000 in ?? ()
#12 0x000000000c79c200 in ?? ()
#13 0x00007ffcd285b908 in ?? ()
#14 0x0000000000000000 in ?? ()
```

**Comment by sfan5** [comment]
https://irc.minetest.net/minetest-dev/2023-12-21#i_6141039

**Comment by SmallJoker** [comment]
Which builds does this affect? MSVC, MinGW or both?

**Comment by sfan5** [comment]
Only MinGW it appears.

**Comment by sfan5** [comment]
On IRC it was speculated that this is actually the long-unfixed https://github.com/msys2/MINGW-packages/issues/2519, which is something we've been dealing with intermittently (see #12022).

**Comment by sfan5** [comment]
For the record: switching to an [LLVM toolchain](https://github.com/mstorsjo/llvm-mingw) would fix this issue.
