### ISSUE TITLE
Arithmetic exception with [crack texture modifier

### ISSUE THREAD

**Issue by a-tour-ist** [minetest/minetest#14241]
### Minetest version

a7eaee77ca0800553589b8ed716a69451496970b

### Active renderer

OpenGL 4.6

### Irrlicht device

X11

### Operating system and version

Manjaro Linux

### Summary

when setting the tile count to 0 in `[crack:<t>:<n>:<p>` the client crashes.

```
Thread 1 "minetest" received signal SIGFPE, Arithmetic exception.
0x0000555555911b9b in irr::core::dimension2d<unsigned int>::operator/ (this=0x7fffffffb61c, scale=@0x7fffffffb670: 0) at /home/tour/minetest/lib/irrlichtmt/include/dimension2d.h:83
83					return dimension2d<T>(Width/scale, Height/scale);
#0  0x0000555555911b9b in irr::core::dimension2d<unsigned int>::operator/ (this=0x7fffffffb61c, scale=@0x7fffffffb670: 0) at /home/tour/minetest/lib/irrlichtmt/include/dimension2d.h:83
#1  0x000055555590bb73 in create_crack_image (crack=0x555558fbec10, frame_index=1, size=..., tiles=0 '\000', driver=0x555556734df0) at /home/tour/minetest/src/client/tile.cpp:2470
#2  0x000055555590bf1c in draw_crack (crack=0x555558fbec10, dst=0x55556059ac10, use_overlay=false, frame_count=1, progression=1, driver=0x555556734df0, tiles=0 '\000') at /home/tour/minetest/src/client/tile.cpp:2525
#3  0x0000555555904027 in TextureSource::generateImagePart (this=0x5555569b6190, part_of_name="[crack:0:1:1", baseimg=@0x7fffffffbc10: 0x55556059ac10, source_image_names=std::set with 1 element = {...}) at /home/tour/minetest/src/client/tile.cpp:1303
#4  0x000055555590311b in TextureSource::generateImage (this=0x5555569b6190, name="blank.png^[crack:0:1:1", source_image_names=std::set with 1 element = {...}) at /home/tour/minetest/src/client/tile.cpp:1066
#5  0x000055555590083c in TextureSource::generateTexture (this=0x5555569b6190, name="blank.png^[crack:0:1:1") at /home/tour/minetest/src/client/tile.cpp:644
#6  0x00005555559003ae in TextureSource::getTextureId (this=0x5555569b6190, name="blank.png^[crack:0:1:1") at /home/tour/minetest/src/client/tile.cpp:508
#7  0x0000555555900d74 in TextureSource::getTexture (this=0x5555569b6190, name="blank.png^[crack:0:1:1", id=0x0) at /home/tour/minetest/src/client/tile.cpp:697
#8  0x000055555598eb3b in GUIFormSpecMenu::parseImage (this=0x555560ad4d80, data=0x7fffffffc670, element="1,1;5,5;blank.png^[crack:0:1:1") at /home/tour/minetest/src/gui/guiFormSpecMenu.cpp:790
#9  0x00005555559a215b in GUIFormSpecMenu::parseElement (this=0x555560ad4d80, data=0x7fffffffc670, element="\nimage[1,1;5,5;blank.png^[crack:0:1:1") at /home/tour/minetest/src/gui/guiFormSpecMenu.cpp:2888
#10 0x00005555559a4a08 in GUIFormSpecMenu::regenerateGui (this=0x555560ad4d80, screensize=...) at /home/tour/minetest/src/gui/guiFormSpecMenu.cpp:3392
#11 0x00005555559feff4 in GUIModalMenu::draw (this=0x555560ad4d80) at /home/tour/minetest/src/gui/modalMenu.cpp:82
#12 0x000055555596ae4c in irr::gui::IGUIElement::draw (this=0x5555569f65f0) at /home/tour/minetest/lib/irrlichtmt/include/IGUIElement.h:337
#13 0x0000555555e70351 in irr::gui::CGUIStaticText::draw (this=0x5555569f65f0) at /home/tour/minetest/lib/irrlichtmt/source/Irrlicht/CGUIStaticText.cpp:141
#14 0x000055555596ae4c in irr::gui::IGUIElement::draw (this=0x555556736758) at /home/tour/minetest/lib/irrlichtmt/include/IGUIElement.h:337
#15 0x0000555555e50278 in irr::gui::CGUIEnvironment::drawAll (this=0x555556736750, useScreenSize=true) at /home/tour/minetest/lib/irrlichtmt/source/Irrlicht/CGUIEnvironment.cpp:188
#16 0x000055555589e984 in DrawHUD::run (this=0x55555f1e8b40, context=...) at /home/tour/minetest/src/client/render/plain.cpp:71
#17 0x000055555589ac2a in RenderPipeline::run (this=0x55555f633530, context=...) at /home/tour/minetest/src/client/render/pipeline.cpp:286
#18 0x00005555558953ec in RenderingCore::draw (this=0x55555f636490, _skycolor=..., _show_hud=true, _show_minimap=false, _draw_wield_tool=true, _draw_crosshair=true) at /home/tour/minetest/src/client/render/core.cpp:52
#19 0x00005555558a76ed in RenderingEngine::draw_scene (this=0x55555647ce00, skycolor=..., show_hud=true, show_minimap=false, draw_wield_tool=true, draw_crosshair=true) at /home/tour/minetest/src/client/renderingengine.cpp:323
#20 0x000055555580d6a0 in Game::drawScene (this=0x7fffffffd2c0, graph=0x7fffffffd0c0, stats=0x7fffffffd080) at /home/tour/minetest/src/client/game.cpp:4325
#21 0x000055555580cb60 in Game::updateFrame (this=0x7fffffffd2c0, graph=0x7fffffffd0c0, stats=0x7fffffffd080, dtime=0.0167430006, cam=...) at /home/tour/minetest/src/client/game.cpp:4200
#22 0x00005555557fb4d4 in Game::run (this=0x7fffffffd2c0) at /home/tour/minetest/src/client/game.cpp:1315
#23 0x00005555558103e0 in the_game (kill=0x5555563f26c0 <porting::g_killed>, input=0x5555569e7000, rendering_engine=0x55555647ce00, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7fffffffd5d4) at /home/tour/minetest/src/client/game.cpp:4597
#24 0x00005555557915cc in ClientLauncher::run (this=0x7fffffffda40, start_data=..., cmd_args=...) at /home/tour/minetest/src/client/clientlauncher.cpp:264
#25 0x0000555555d1cb04 in main (argc=2, argv=0x7fffffffdee8) at /home/tour/minetest/src/main.cpp:266
```

found after some more testing after #14223 was found

### Steps to reproduce

view the following formspec:

```
size[5,5]
image[0,0;1,1;blank.png^[crack:0:1:1]
```

**Comment by SmallJoker** [comment]
ed7d4037b
