### ISSUE TITLE
Random segfaults when connecting to a server

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#1434]
Sometimes, the game segfaults when connecting to a server (singleplayer too). The segfaults are quite random.

EDIT: Irrlicht version is 1.8.1.

Here is a backtrace (sorry, build wasn't a debug one):
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000137d3a0 in ?? ()
(gdb) bt full
#0  0x000000000137d3a0 in ?? ()
No symbol table info available.
#1  0x0000000000862338 in irr::gui::CGUIEnvironment::OnPostRender(unsigned int) ()
No symbol table info available.
#2  0x000000000068e4b4 in draw_load_screen(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, irr::IrrlichtDevice*, irr::gui::IGUIEnvironment*, irr::gui::IGUIFont*, float, int, bool) ()
No symbol table info available.
#3  0x00000000006b9a0c in the_game(bool&, bool, InputHandler*, irr::IrrlichtDevice*, irr::gui::IGUIFont*, std::string, std::string, std::string, std::string, unsigned short, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, ChatBackend&, SubgameSpec const&, bool) ()
No symbol table info available.
#4  0x000000000055f3d2 in main ()
No symbol table info available.
```

**Comment by sapier** [comment]
Is this bug still valid?
If not I'm gonna close it in about a week
