### ISSUE TITLE
Segfault at startup

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#1435]
Happens randomly, here is a backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1578
(gdb) #0  __memcpy_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1578
No locals.
#1  0x00007ffff49d7cd0 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00007ffff49cf4a5 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00000000006d6f93 in operator<< <char, std::char_traits<char>, std::allocator<char> > (__str=..., __os=...) at /usr/include/c++/4.8/bits/basic_string.h:2758
No locals.
#4  log_printline (lev=LMT_VERBOSE, text=...) at /home/nathanael/Minetest/src/log.cpp:104
        threadname = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe865c8 "main"}}
        i = <optimized out>
        levelname = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x127ce98 "VERBOSE"}}
        os = <incomplete type>
#5  0x00000000006d7ec1 in printbuf (this=0xe528a0 <verbosebuf>) at /home/nathanael/Minetest/src/log.cpp:141
No locals.
#6  bufchar (c=10 '\n', this=0xe528a0 <verbosebuf>) at /home/nathanael/Minetest/src/log.cpp:148
No locals.
#7  Logbuf::overflow (this=0xe528a0 <verbosebuf>, c=10) at /home/nathanael/Minetest/src/log.cpp:129
No locals.
#8  0x00007ffff49cef24 in std::ostream::put(char) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#9  0x000000000056bafb in endl<char, std::char_traits<char> > (__os=...) at /usr/include/c++/4.8/ostream:565
No locals.
#10 operator<< (__pf=<optimized out>, this=0xe52420 <verbosestream>) at /usr/include/c++/4.8/ostream:113
No locals.
#11 ScriptApiBase::loadScript (this=0x124aa00, scriptpath=...) at /home/nathanael/Minetest/src/script/cpp_api/s_base.cpp:128
        ret = <optimized out>
#12 0x000000000068b370 in GUIEngine::loadMainMenuScript (this=this@entry=0x123ad30) at /home/nathanael/Minetest/src/guiEngine.cpp:224
        script = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x124a1f8 "/home/nathanael/Minetest/bin/../builtin/init.lua"}}
#13 0x000000000068bba2 in GUIEngine::GUIEngine (this=0x123ad30, dev=<optimized out>, parent=<optimized out>, menumgr=<optimized out>, smgr=<optimized out>, data=<optimized out>, kill=@0xe72ea0: false)
    at /home/nathanael/Minetest/src/guiEngine.cpp:195
        soundfetcher = {<OnDemandSoundFetcher> = {_vptr.OnDemandSoundFetcher = 0xafc800 <vtable for MenuMusicFetcher+16>}, m_fetched = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, 
                _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffc300, _M_right = 0x7fffffffc300}, _M_node_count = 0}}}}
        rect = {UpperLeftCorner = {X = 4, Y = 0}, LowerRightCorner = {X = 504, Y = 20}}
        t = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1248f68 "Minetest 0.4.9-323-g58f0d24-dirty"}}
#14 0x00000000006de9e0 in main (argc=<optimized out>, argv=<optimized out>) at /home/nathanael/Minetest/src/main.cpp:1665
        driver = <optimized out>
        temp = <optimized out>
        menudata = {servername = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, serverdescription = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, address = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe93818 "digitalaudioconcepts.com"}}, port = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x12027d8 "30000"}}, name = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe963b8 "nore"}}, password = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, enable_public = false, 
          selected_world = 0, simple_singleplayer_mode = false, errormessage = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}}
        worldspecs = {<std::_Vector_base<WorldSpec, std::allocator<WorldSpec> >> = {_M_impl = {<std::allocator<WorldSpec>> = {<__gnu_cxx::new_allocator<WorldSpec>> = {<No data fields>}, <No data fields>}, 
              _M_start = 0x123cba0, _M_finish = 0x123e0e8, _M_end_of_storage = 0x123e3a0}}, <No data fields>}
        newport = <optimized out>
        worldspec = {path = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, name = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, gameid = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}}
        simple_singleplayer_mode = false
        current_playername = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1202808 "inv£lid"}}
        gamespec = {id = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, path = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, gamemods_path = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, addon_mods_paths = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, 
                _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffc790, _M_right = 0x7fffffffc790}, _M_node_count = 0}}}, name = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, menuicon_path = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}}
        current_password = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}
        current_address = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1201a38 "does-not-exist"}}
        current_port = 0
        text = <optimized out>
        retval = 0
        cmd_args = {m_settings = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<No data fields>}, <No data fields>}, 
                _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffc6e8, _M_right = 0x7fffffffc6e8}, _M_node_count = 0}}}, m_defaults = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<No data fields>}, <No data fields>}, 
                _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffc718, _M_right = 0x7fffffffc718}, _M_node_count = 0}}}, m_mutex = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}}
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        screenW = <optimized out>
        chat_backend = {m_console_buffer = {m_scrollback = 500, m_unformatted = {<std::_Vector_base<ChatLine, std::allocator<ChatLine> >> = {
                _M_impl = {<std::allocator<ChatLine>> = {<__gnu_cxx::new_allocator<ChatLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, 
            m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = {<std::_Vector_base<ChatFormattedLine, std::allocator<ChatFormattedLine> >> = {
                _M_impl = {<std::allocator<ChatFormattedLine>> = {<__gnu_cxx::new_allocator<ChatFormattedLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, 
                  _M_end_of_storage = 0x0}}, <No data fields>}, m_empty_formatted_line = {fragments = {<std::_Vector_base<ChatFormattedFragment, std::allocator<ChatFormattedFragment> >> = {
                  _M_impl = {<std::allocator<ChatFormattedFragment>> = {<__gnu_cxx::new_allocator<ChatFormattedFragment>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, 
                    _M_end_of_storage = 0x0}}, <No data fields>}, first = true}}, m_recent_buffer = {m_scrollback = 6, m_unformatted = {<std::_Vector_base<ChatLine, std::allocator<ChatLine> >> = {
                _M_impl = {<std::allocator<ChatLine>> = {<__gnu_cxx::new_allocator<ChatLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, 
            m_cols = 0, m_rows = 0, m_scroll = 0, m_formatted = {<std::_Vector_base<ChatFormattedLine, std::allocator<ChatFormattedLine> >> = {
                _M_impl = {<std::allocator<ChatFormattedLine>> = {<__gnu_cxx::new_allocator<ChatFormattedLine>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, 
                  _M_end_of_storage = 0x0}}, <No data fields>}, m_empty_formatted_line = {fragments = {<std::_Vector_base<ChatFormattedFragment, std::allocator<ChatFormattedFragment> >> = {
                  _M_impl = {<std::allocator<ChatFormattedFragment>> = {<__gnu_cxx::new_allocator<ChatFormattedFragment>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, 
                    _M_end_of_storage = 0x0}}, <No data fields>}, first = true}}, m_prompt = {m_prompt = {static npos = 18446744073709551615, 
              _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, _M_p = 0x1202728 L"]"}}, m_line = {static npos = 18446744073709551615, 
              _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, 
                _M_p = 0xe50298 <_ZNSbIwSt11char_traitsIwESaIwEE4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> L""}}, 
            m_history = {<std::_Vector_base<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >> = {
                _M_impl = {<std::allocator<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >> = {<__gnu_cxx::new_allocator<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, m_history_index = 0, m_history_limit = 500, m_cols = 0, m_view = 0, m_cursor = 0, 
            m_nick_completion_start = 0, m_nick_completion_end = 0}}
        __debug_stacker = {m_stack = 0xe87d20, m_overflowed = false}
        commanded_gamespec = {id = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, path = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, gamemods_path = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, addon_mods_paths = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, 
                _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0x0, _M_left = 0x7fffffffc640, _M_right = 0x7fffffffc640}, _M_node_count = 0}}}, name = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}, menuicon_path = {
            static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}}
        skip_main_menu = false
        bits = <optimized out>
        camera = <optimized out>
        error_message = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<wchar_t>> = {<__gnu_cxx::new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe50298 <_ZNSbIwSt11char_traitsIwESaIwEE4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> L""}}
        loglevel = <optimized out>
        address = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe93818 "digitalaudioconcepts.com"}}
        driverType = <optimized out>
        receiver = {<irr::IEventReceiver> = {_vptr.IEventReceiver = 0xb05130 <vtable for MyEventReceiver+16>}, leftclicked = false, rightclicked = false, leftreleased = false, rightreleased = false, left_active = false, 
          middle_active = false, right_active = false, mouse_wheel = 0, keyIsDown = {<std::list<KeyPress, std::allocator<KeyPress> >> = {<std::_List_base<KeyPress, std::allocator<KeyPress> >> = {
                _M_impl = {<std::allocator<std::_List_node<KeyPress> >> = {<__gnu_cxx::new_allocator<std::_List_node<KeyPress> >> = {<No data fields>}, <No data fields>}, _M_node = {_M_next = 0x7fffffffc5a0, 
                    _M_prev = 0x7fffffffc5a0}}}, <No data fields>}, _vptr.KeyList = 0xb04f70 <vtable for KeyList+16>}, 
          keyWasDown = {<std::list<KeyPress, std::allocator<KeyPress> >> = {<std::_List_base<KeyPress, std::allocator<KeyPress> >> = {
                _M_impl = {<std::allocator<std::_List_node<KeyPress> >> = {<__gnu_cxx::new_allocator<std::_List_node<KeyPress> >> = {<No data fields>}, <No data fields>}, _M_node = {_M_next = 0x7fffffffc5b8, 
                    _M_prev = 0x7fffffffc5b8}}}, <No data fields>}, _vptr.KeyList = 0xb04f70 <vtable for KeyList+16>}}
        irr_logger = <optimized out>
        password = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}
        screenH = <optimized out>
        driver = 0x110fff0
        commanded_world = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}
        commanded_worldname = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe4fd98 <_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4+24> ""}}
        logfile = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe93728 "debug.txt"}}
        port = 30000
        device = 0xeb55c0
        irr_log_level = {irr::ELL_NONE, irr::ELL_ERROR, irr::ELL_WARNING, irr::ELL_INFORMATION, irr::ELL_DEBUG}
        font_path = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe90458 "/home/nathanael/Minetest/bin/../fonts/fontlucida.png"}}
        allowed_options = {_M_t = {
            _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ValueSpec> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ValueSpec> > >> = {<No data fields>}, <No data fields>}, 
              _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0xe867a0, _M_left = 0xe86e50, _M_right = 0xe869f0}, _M_node_count = 24}}}
        params = {DeviceType = irr::EIDT_BEST, DriverType = irr::video::EDT_OPENGL, WindowSize = {Width = 800, Height = 600}, Bits = 24 '\030', ZBufferBits = 16 '\020', Fullscreen = false, Stencilbuffer = false, 
          Vsync = false, AntiAlias = 0 '\000', HandleSRGB = false, WithAlphaChannel = false, Doublebuffer = true, IgnoreInput = false, Stereobuffer = false, HighPrecisionFPU = true, EventReceiver = 0x7fffffffc580, 
          WindowId = 0x0, LoggingLevel = irr::ELL_INFORMATION, DisplayAdapter = 0, DriverMultithreaded = false, UsePerformanceTimer = true, SDK_version_do_not_use = 0xb0459c "1.8.1"}
        skin = <optimized out>
        font = 0x1209e40
        text_height = <optimized out>
        ret = <optimized out>
        kill = @0xe72ea0: false
        run_dedicated_server = <optimized out>
        playername = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe963b8 "nore"}}
        fullscreen = <optimized out>
        vsync = <optimized out>
        smgr = 0x11fbe30
        first_loop = false
        fsaa = <optimized out>
        driverstring = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe8de78 "opengl"}}
        random_input = <optimized out>
        input = 0x12097b0
```

**Comment by sapier** [comment]
Code causing this segfault doesn't exist any longer if there's no confirmation this bug is still there I'm gonna close is in about a week.
