### ISSUE TITLE
Random crashes in logging

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#1447]
It's so broken even gdb breaks...
```
(gdb) bt full
#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
No locals.
#1  0x00007ffff3d7e5e0 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00007ffff3d75db5 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x000000000073f329 in log_printline (lev=LMT_VERBOSE, text=...)
    at /home/stefan/minetest/src/log.cpp:106
        i = <optimized out>
        threadname = <optimized out>
#4  0x000000000073fe52 in Logbuf::bufchar (this=0xb72c48 <verbosebuf>, 
    c=<optimized out>) at /home/stefan/minetest/src/log.cpp:153
No locals.
#5  0x000000000073fe1b in Logbuf::overflow (this=0x7fffd82beff0, c=10)
    at /home/stefan/minetest/src/log.cpp:131
No locals.
#6  0x00007ffff3d75834 in std::ostream::put(char) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#7  0x00007ffff3d75a62 in std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x0000000000606935 in ScriptApiBase::loadScript (this=0xf8bce8, 
    scriptpath=...) at /home/stefan/minetest/src/script/cpp_api/s_base.cpp:128
        L = <optimized out>
#9  0x00000000006ff6ab in GUIEngine::loadMainMenuScript (this=0x7fffffffbb00)
    at /home/stefan/minetest/src/guiEngine.cpp:238
        script = <optimized out>
#10 0x00000000006ff3eb in GUIEngine::GUIEngine (this=0x7fffffffbb00, 
    dev=<optimized out>, parent=<optimized out>, menumgr=<optimized out>, 
    smgr=<optimized out>, data=<optimized out>, kill=@0xb93460: false)
    at /home/stefan/minetest/src/guiEngine.cpp:209
No locals.
#11 0x00000000007453b5 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/stefan/minetest/src/main.cpp:1722
        driver = <optimized out>
        newport = <optimized out>
        worldspecs = warning: Auf ein nicht zugeordnetes DWARF-Register #-1 gestoßen.

/build/buildd/gdb-7.7/gdb/regcache.c:178: internal-error: register_size: Assertion `regnum >= 0 && regnum < (gdbarch_num_regs (gdbarch) + gdbarch_num_pseudo_reg---Type <return> to continue, or q <return> to quit---
s (gdbarch))' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```

**Comment by MoNTE48** [comment]
This remains actually?

**Comment by est31** [comment]
I think this bug may have been related to the bug c350cfb50b3bf81c075a80307adb15393ea773d0 fixed. Anyway, its been a long time since I last saw this segfault, so I believe its fixed. Reopen if you can still report it.
