### ISSUE TITLE
Creating a particle spawner without a texture and a texture pool causes the client to crash

### ISSUE THREAD

**Issue by andriyndev** [minetest/minetest#14708]
### Minetest version

```true
Minetest 5.9.0-dev-debug-e82f71e41 (Linux)
Using LuaJIT 2.1.1713773202
Built by GCC 11.4
Running on Linux/6.5.0-35-generic x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Linux Mint 21.3 Cinnamon

### CPU model

Intel© Core™ i3-7100U CPU @ 2.40GHz × 2

### GPU model

Intel Corporation HD Graphics 620

### Summary

The client crashes with "abort" when the server starts a particle spawner without specifying both texture and texture pool. The issue is relevant only for 5.9-dev while 5.8 uses a default texture in this case. The error:
```
minetest: /home/andrii/git/minetest/src/client/particles.cpp:1011: static irr::video::SMaterial ParticleManager::getMaterialForParticle(const ClientParticleTexRef&): Assertion `texture.ref' failed.
Aborted (core dumped)
```
Backtrace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=138025884817792) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=138025884817792) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=138025884817792, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007d88a9442476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007d88a94287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007d88a942871b in __assert_fail_base (fmt=0x7d88a95dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x621fa9b2a172 "texture.ref", file=0x621fa9b2a028 "/home/andrii/git/minetest/src/client/particles.cpp", line=1011, 
    function=<optimized out>) at ./assert/assert.c:92
#6  0x00007d88a9439e96 in __GI___assert_fail (assertion=0x621fa9b2a172 "texture.ref", file=0x621fa9b2a028 "/home/andrii/git/minetest/src/client/particles.cpp", line=1011, 
    function=0x621fa9b2a110 "static irr::video::SMaterial ParticleManager::getMaterialForParticle(const ClientParticleTexRef&)") at ./assert/assert.c:101
#7  0x0000621fa940317d in ParticleManager::getMaterialForParticle (texture=...) at /home/andrii/git/minetest/src/client/particles.cpp:1011
#8  0x0000621fa940322b in ParticleManager::addParticle (this=0x621fac8762e0, toadd=std::unique_ptr<Particle> = {...}) at /home/andrii/git/minetest/src/client/particles.cpp:1021
#9  0x0000621fa940082a in ParticleSpawner::spawnParticle (this=0x621fb3f33930, env=0x621fac873330, radius=192, attached_absolute_pos_rot_matrix=0x0) at /home/andrii/git/minetest/src/client/particles.cpp:496
#10 0x0000621fa9400a9f in ParticleSpawner::step (this=0x621fb3f33930, dtime=0.0177410003, env=0x621fac873330) at /home/andrii/git/minetest/src/client/particles.cpp:532
#11 0x0000621fa9401b76 in ParticleManager::stepSpawners (this=0x621fac8762e0, dtime=0.0177410003) at /home/andrii/git/minetest/src/client/particles.cpp:699
#12 0x0000621fa94019ad in ParticleManager::step (this=0x621fac8762e0, dtime=0.0177410003) at /home/andrii/git/minetest/src/client/particles.cpp:672
#13 0x0000621fa9373d19 in Game::updateFrame (this=0x7ffd7586f320, graph=0x7ffd7586f100, stats=0x7ffd7586f0c0, dtime=0.0177410003, cam=...) at /home/andrii/git/minetest/src/client/game.cpp:4110
#14 0x0000621fa93623b7 in Game::run (this=0x7ffd7586f320) at /home/andrii/git/minetest/src/client/game.cpp:1224
#15 0x0000621fa937783b in the_game (kill=0x621fa9ff9901 <porting::g_killed>, input=0x621fabf7c460, rendering_engine=0x621fabc322b0, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7ffd7586f654)
    at /home/andrii/git/minetest/src/client/game.cpp:4570
#16 0x0000621fa92f80ca in ClientLauncher::run (this=0x7ffd7586f960, start_data=..., cmd_args=...) at /home/andrii/git/minetest/src/client/clientlauncher.cpp:209
#17 0x0000621fa98de72a in main (argc=1, argv=0x7ffd7586fdf8) at /home/andrii/git/minetest/src/main.cpp:263
```

### Steps to reproduce

Create a mod with the following code:
```
minetest.register_chatcommand("crash_minetest", {
    description = "Crash Minetest",
    func = function(name, param)
        local player = minetest.get_player_by_name(name)

        minetest.add_particlespawner({
            amount = 50,
            time = 0.01,
            minpos = player:get_pos(),
            maxpos = player:get_pos(),
            minvel = vector.new(-10, -10, -10),
            maxvel = vector.new(10, 10, 10),
            minexptime = 0.3,
            maxexptime = 0.3,
            minsize = 0.4,
            maxsize = 0.4
        })
    end
})
```
Run the `/crash_minetest` chat command.

**Comment by SmallJoker** [comment]
Introduced in f8bff346.

Does this fix your issue?
```C++
diff --git a/src/client/particles.cpp b/src/client/particles.cpp
index 638505846..c19282424 100644
--- a/src/client/particles.cpp
+++ b/src/client/particles.cpp
@@ -1008,7 +1008,6 @@ video::SMaterial ParticleManager::getMaterialForParticle(const ClientParticleTex
                        video::EMFN_MODULATE_1X,
                        video::EAS_TEXTURE | video::EAS_VERTEX_COLOR);
        material.BlendOperation = blendop;
-       assert(texture.ref);
        material.setTexture(0, texture.ref);
 
        return material;
```
material textures may be nullptr, so this should be fine.

**Comment by andriyndev** [comment]
Thank you, I'll check it tomorrow evening

**Comment by andriyndev** [comment]
I've just checked, yes, it fixed the issue.

**Comment by SmallJoker** [comment]
670bb32
