### ISSUE TITLE
Regression error in mod_translation_updater

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#14802]
### Minetest version

Current origin/master, commit id 9a1501ae89ffe79c38dbd6756c9e7ed647dd7dc1

### Operating system and version

Debian GNU/Linux 12 (bookworm)

### Summary

When attempting to run the translation updater on the mineclonia repository:

```
Running on folder /home/eam/src/mineclonia
Updating translations for mcl_privs
Done.
Updating translations for mcl_temp_helper_recipes
Traceback (most recent call last):
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 504, in <module>
    main()
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 119, in main
    update_folder(os.path.abspath("./"))
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 493, in update_folder
    run_all_subfolders(os.path.join(folder, "mods"))
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 502, in run_all_subfolders
    update_folder(modfolder)
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 495, in update_folder
    run_all_subfolders(folder)
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 502, in run_all_subfolders
    update_folder(modfolder)
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 497, in update_folder
    update_mod(folder)
  File "/home/eam/src/minetest/util/mod_translation_updater.py", line 476, in update_mod
    (data, templ) = generate_template(folder, modname)
    ^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

Git bisect finds that its a regression of 815b5cb0867c2011be7031b74331b99de94326e4.

### Steps to reproduce

Clone the mineclonia git repository and attempt to run the mod translation updater in it.

```sh
git clone https://codeberg.org/mineclonia/mineclonia
cd mineclonia
mod_translation_updater.py -r ./mods
```

**Comment by SmallJoker** [comment]
95e77bd7c
