### ISSUE TITLE
Minetest 0.4.10 Segmentation fault in Mapgen::calcLighting using Wasteland 0.2.2 game

### ISSUE THREAD

**Issue by Talkless** [minetest/minetest#1499]
Game crashes in first few seconds while generating world.

Minetest, Carbone games does not crash.

GDB output:
```
Irrlicht log: Could not open file of texture: character.png
{["y"] = 12, ["x"] = -28, ["z"] = 10}

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcdc52700 (LWP 12905)]
0x00000000007eff01 in Mapgen::calcLighting(irr::core::vector3d<short>, irr::core::vector3d<short>) ()
(gdb) bt
#0  0x00000000007eff01 in Mapgen::calcLighting(irr::core::vector3d<short>, irr::core::vector3d<short>) ()
#1  0x000000000064ba03 in LuaVoxelManip::l_calc_lighting(lua_State*) ()
#2  0x00000000005f6a36 in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#3  0x00007ffff6bd9af1 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#4  0x00007ffff6c1cd00 in lua_pcall () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x00000000005f6be2 in script_run_callbacks(lua_State*, int, RunCallbacksMode) ()
#6  0x00000000005fd466 in ScriptApiEnv::environment_OnGenerated(irr::core::vector3d<short>, irr::core::vector3d<short>, unsigned int) ()
#7  0x00000000007160a4 in EmergeThread::Thread() ()
#8  0x00000000005e73d3 in JThread::TheThread(void*) ()
#9  0x00007ffff67b2182 in start_thread (arg=0x7fffcdc52700) at pthread_create.c:312
#10 0x00007ffff55b530d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
"layout asm" gives:
```
   +----------------------------------------------------------------------------------------------------------------------------------------+
   |0x7efef0 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+304>      add    %ecx,%edx                                                |
   |0x7efef2 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+306>      movswl %ax,%ecx                                                 |
   |0x7efef5 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+309>      imul   %ecx,%edx                                                |
   |0x7efef8 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+312>      add    %ebx,%edx                                                |
   |0x7efefa <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+314>      mov    %edx,%r13d                                               |
   |0x7efefd <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+317>      lea    (%r11,%r13,4),%rbp                                       |
  >|0x7eff01 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+321>      cmpw   $0x7f,0x0(%rbp)                                          |
   |0x7eff06 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+326>      jne    0x7efe80 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsE|
   |0x7eff0c <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+332>      mov    0x10(%rsp),%r10d                                         |
   |0x7eff11 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+337>      cmp    %r10d,0xc(%rsp)                                          |
   |0x7eff16 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+342>      jge    0x7efe93 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsE|
   |0x7eff1c <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+348>      cmp    %di,0x32(%rsp)                                           |
   |0x7eff21 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+353>      lea    (%rdx,%r14,1),%ebx                                       |
   |0x7eff25 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+357>      movswl %di,%r13d                                                |
   |0x7eff29 <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsEES3_+361>      jle    0x7eff4e <_ZN6Mapgen12calcLightingEN3irr4core8vector3dIsE|
   +----------------------------------------------------------------------------------------------------------------------------------------+
```
Kubuntu 14.04 amd64
Minetest and Irrlicht 1.8.1 compiled from source (with -g -O3 -march=native).

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/ef8ed5d127f2c698586efdfd254c8e5c7ba66f19
