### ISSUE TITLE
minetest.decompress() freezes if called on an empty file with zstd compression

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#15042]
### Minetest version

```true
Tested Minetest 5.7.0 - Minetest 5.9.0
```

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### Summary

I was trying out zstd compression when I tried to read a file that was empty (io.read returns ""), and it locked up Minetest. Ctrl-C was required more than once to shut it down.
The same code using "deflate" instead works fine, decompress() happily returns nil and my code says the read failed.

### Steps to reproduce

Just run `minetest.decompress("", "zstd")`

**Comment by sfan5** [comment]
stuck here
```
Thread 33 (Thread 0x7fffb2a006c0 (LWP 5321) "Server"):
#0  0x00007ffff732f35b in std::basic_istream<char, std::char_traits<char> >::sentry::sentry (this=0x7fffb29f40c7, __in=..., __noskip=true) at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/istream.tcc:50
#1  0x00007ffff73305c1 in std::basic_istream<char, std::char_traits<char> >::read (this=this@entry=0x7fffb29fc3e0, __s=__s@entry=0x7fffb29f8180 "\300\201\237\262\377\177", __n=__n@entry=16384) at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/istream.tcc:705
#2  0x0000555555efa012 in decompressZstd (is=..., os=...) at /home/stefan/minetest/src/serialization.cpp:262
#3  0x0000555555c3bb1f in ModApiUtil::l_decompress (L=0x7fffeebc0380, L@entry=<error reading variable: value has been optimized out>) at /home/stefan/minetest/src/script/lua_api/l_util.cpp:365
#4  0x0000555555b79fec in script_exception_wrapper (L=0x7fffeebc0380, f=<optimized out>) at /home/stefan/minetest/src/script/common/c_internal.cpp:41
#5  0x00007ffff7ac7f7b in lj_BC_FUNCCW () at buildvm_x86.dasc:857
#6  0x00007ffff7adc12a in lua_pcall (L=0x7fffeebc0380, nargs=<optimized out>, nresults=1, errfunc=<optimized out>) at /usr/src/debug/luajit/LuaJIT-ae4735f621d89d84758769b76432d2319dda9827/src/lj_api.c:1122
```
