### ISSUE TITLE
15286 (EGL) breaks Minetest start on Linux/Fedora with NVidia drivers.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#15313]
### Minetest version

```true
Build from main
```

### Irrlicht device

X11

### Operating system and version

Fedora 40

### CPU model

Intel

### GPU model

NVidia

### Active renderer

OpenGL 4.6.0

### Summary

```
2024-10-22 17:03:01: ERROR[Main]: Irrlicht: Could not create EGL surface.

Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x0000000000c60471 in irr::video::COpenGLDriver::~COpenGLDriver() ()
(gdb) bt
#0  0x0000000000c60471 in irr::video::COpenGLDriver::~COpenGLDriver() ()
#1  0x0000000000c60723 in virtual thunk to irr::video::COpenGLDriver::~COpenGLDriver() ()
#2  0x0000000000c6ce03 in irr::video::createOpenGLDriver(irr::SIrrlichtCreationParameters const&, irr::io::IFileSystem*, irr::video::IContextManager*) ()
#3  0x0000000000c0165f in irr::CIrrDeviceLinux::createDriver() ()
#4  0x0000000000c0c6fe in irr::CIrrDeviceLinux::CIrrDeviceLinux(irr::SIrrlichtCreationParameters const&) ()
#5  0x0000000000bfff30 in createDeviceEx ()
#6  0x00000000005f9e12 in RenderingEngine::RenderingEngine(MyEventReceiver*) ()
#7  0x00000000004fea74 in ClientLauncher::init_engine() ()
#8  0x0000000000503d0f in ClientLauncher::run(GameStartData&, Settings const&) ()
#9  0x00000000004d13d8 in main ()
```

Works fine with https://github.com/minetest/minetest/commit/aa273119f292e52df8d99f663df5337bac31556d reverted.

### Steps to reproduce

Start Minetest using the closed source NVidia driver on Fedora 40.

**Comment by lhofhansl** [comment]
There also appears to be no way to switch to GLX anymore. I did not notice the radical move in the PR.

@sfan5 FYI.

**Comment by sfence** [comment]
Not a problem on Arch linux:

```
glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 560.35.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 560.35.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 560.35.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

X11 build from master, verified in GDB that my build use same code: 


```
Thread 1 "minetest" hit Breakpoint 1, irr::video::CEGLManager::generateSurface
    (this=0x5555565bb5f0)
    at /src/GNU_sources/minetest/minetest_master/irr/src/CEGLManager.cpp:135
135             EglSurface = eglCreateWindowSurface(EglDisplay, EglConfig, EglWindow, 0);
(gdb) continue

```

**Comment by SmallJoker** [comment]
@lhofhansl 

1. Which driver version?
2. Would you please be so nice to provide a backtrace using a debug build?
3. valgrind in combination, if possible. That might unveil additional issues.

**Comment by lhofhansl** [comment]
```
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.7
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.7
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.1.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

$ __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 560.35.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 560.35.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 560.35.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by lhofhansl** [comment]
Maybe this is a problem: __GLX_VENDOR_LIBRARY_NAME=nvidia
I'll try right now

**Comment by lhofhansl** [comment]
Maybe until we figure this out, we can bring back GLX as a compile time option?

**Comment by grorp** [comment]
> Maybe until we figure this out, we can bring back GLX as a compile time option?

This close to the 5.10.0 release, reverting #15286 is the only solution that makes sense. We don't want to delay the release because of this. We don't want users no longer being able to start Luanti. We definitely don't want to ask users to "just compile it yourself with this or that option set, perhaps it will work again then".

**Comment by lhofhansl** [comment]
Here's a similar issue: https://github.com/obsproject/obs-studio/issues/6984
The author somehow fixed with a config change, and there's a PR as well.
