### ISSUE TITLE
Singleplayer segfaults if server rejects client

### ISSUE THREAD

**Issue by kahrl** [minetest/minetest#2219]
To reproduce, start a singleplayer world with the following (or a similar) callback:
```
minetest.register_on_prejoinplayer(function(name, ip)
        return "Go away."
end)
```
Backtrace:
```
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../bin/minetest...
done.
(gdb) r
Starting program: /home/kahrl/minetest/bin/minetest 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe8e55700 (LWP 6029)]
[New Thread 0x7fffe0654700 (LWP 6030)]
[New Thread 0x7fffe3fff700 (LWP 6031)]
[New Thread 0x7fffe37fe700 (LWP 6032)]
[Thread 0x7fffe37fe700 (LWP 6032) exited]
[Thread 0x7fffe3fff700 (LWP 6031) exited]
[Thread 0x7fffe8e55700 (LWP 6029) exited]
[Thread 0x7fffe0654700 (LWP 6030) exited]
Irrlicht log: Irrlicht Engine version 1.8.0
Irrlicht log: Linux 3.16.5-gentoo #3 SMP Mon Nov 10 03:35:43 CET 2014 x86_64
[New Thread 0x7fffe0654700 (LWP 6033)]
Irrlicht log: Using renderer: OpenGL 3.0
Irrlicht log: Gallium 0.4 on AMD BARTS: X.Org
Irrlicht log: OpenGL driver version is 1.2 or better.
Irrlicht log: GLSL version: 1.3
[New Thread 0x7fffe07c3700 (LWP 6034)]
[New Thread 0x7fffe8e55700 (LWP 6035)]
[New Thread 0x7fffe37fe700 (LWP 6036)]
[New Thread 0x7fffe3fff700 (LWP 6037)]
[New Thread 0x7fffdf34e700 (LWP 6038)]
[Thread 0x7fffe07c3700 (LWP 6034) exited]
[Thread 0x7fffe3fff700 (LWP 6037) exited]
[Thread 0x7fffe37fe700 (LWP 6036) exited]
[Thread 0x7fffdf34e700 (LWP 6038) exited]
[Thread 0x7fffe8e55700 (LWP 6035) exited]
[New Thread 0x7fffe07c3700 (LWP 6039)]
[New Thread 0x7fffdf34e700 (LWP 6040)]
[New Thread 0x7fffe3fff700 (LWP 6041)]
[New Thread 0x7fffe37fe700 (LWP 6042)]
14:57:46: ACTION[main]:         .__               __                   __   
14:57:46: ACTION[main]:   _____ |__| ____   _____/  |_  ____   _______/  |_ 
14:57:46: ACTION[main]:  /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
14:57:46: ACTION[main]: |  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
14:57:46: ACTION[main]: |__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
14:57:46: ACTION[main]:       \/        \/     \/          \/     \/        
14:57:46: ACTION[main]: World at [/home/kahrl/minetest/bin/../worlds/bla]
14:57:46: ACTION[main]: Server for gameid="minetest" listening on 0.0.0.0:58792.
[New Thread 0x7fffe8e55700 (LWP 6043)]
[New Thread 0x7fffde71f700 (LWP 6044)]
14:57:46: ACTION[ServerThread]: Server: Player with the name "singleplayer" tried to connect from 127.0.0.1 but it was disallowed for the following reason: Go away.
14:57:46: ERROR[main]: Access denied. Reason: Go away.
[Thread 0x7fffe8e55700 (LWP 6043) exited]
[Thread 0x7fffde71f700 (LWP 6044) exited]
[Thread 0x7fffe07c3700 (LWP 6039) exited]
[Thread 0x7fffe37fe700 (LWP 6042) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5455186 in sqlite3_finalize () from /usr/lib64/libsqlite3.so.0
(gdb) thread apply all bt full

Thread 14 (Thread 0x7fffe3fff700 (LWP 6041)):
#0  0x00007ffff3bcf7f3 in select () from /lib64/libc.so.6
No symbol table info available.
#1  0x000000000096fade in UDPSocket::WaitData (this=0x10f9090, timeout_ms=50)
    at /home/kahrl/minetest/src/socket.cpp:561
        readset = {fds_bits = {512, 0 <repeats 15 times>}}
        result = 124
        tv = {tv_sec = 0, tv_usec = 12672}
#2  0x000000000075ed7c in con::ConnectionReceiveThread::receive (
    this=0x10f9280) at /home/kahrl/minetest/src/connection.cpp:2110
        packet_maxsize = 1500
        packetdata = {data = 0x7fffe4001150 "", m_size = 1500, 
          refcount = 0x7fffe40010b0}
        packet_queued = true
        loop_count = 0
#3  0x000000000075e0f4 in con::ConnectionReceiveThread::Thread (
    this=0x10f9280) at /home/kahrl/minetest/src/connection.cpp:2034
        sp = {m_profiler = 0xde1d40 <main_profiler>, 
          m_name = "ConnectionReceive: [con(9/0)]", 
          m_timer = 0x7fffe4000b60, m_type = SPT_AVG}
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionReceiveThread::Thread()"
        ThreadIdentifier = <incomplete type>
#4  0x000000000068aa07 in JThread::TheThread (param=0x10f9280)
    at /home/kahrl/minetest/src/jthread/pthread/jthread.cpp:157
        jthread = 0x10f9280
#5  0x00007ffff4fcf1da in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00007ffff3bd6bbd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 13 (Thread 0x7fffdf34e700 (LWP 6040)):
#0  0x00007ffff4fd5731 in sem_timedwait () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000068a4f9 in JSemaphore::Wait (this=0x10f9250, time_ms=50)
    at /home/kahrl/minetest/src/jthread/pthread/jsemaphore.cpp:126
        waittime = {tv_sec = 1422367066, tv_nsec = 767505000}
        now = {tv_sec = 1422367066, tv_usec = 717505}
        __PRETTY_FUNCTION__ = "bool JSemaphore::Wait(unsigned int)"
        sem_wait_retval = 32767
#2  0x00000000007587f6 in con::ConnectionSendThread::Thread (this=0x10f91b0)
    at /home/kahrl/minetest/src/connection.cpp:1276
        sp = {m_profiler = 0xde1d40 <main_profiler>, 
          m_name = "ConnectionSend: [con(9/0)]", m_timer = 0x7fffd4000c60, 
          m_type = SPT_AVG}
        dtime = 0.050999999
        c = {type = con::CONNCMD_NONE, address = {m_addr_family = 0, 
            m_address = {ipv4 = {sin_family = 0, sin_port = 0, sin_addr = {
                  s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, 
              ipv6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, 
                sin6_addr = {__in6_u = {
                    __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {
                      0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, 
                sin6_scope_id = 0}}, m_port = 0}, peer_id = 0, 
          channelnum = 127 '\177', data = {data = 0x0, m_size = 0}, 
          reliable = false, raw = false}
        __PRETTY_FUNCTION__ = "virtual void* con::ConnectionSendThread::Thread()"
        curtime = 732891741
        lasttime = 732891690
        ThreadIdentifier = <incomplete type>
#3  0x000000000068aa07 in JThread::TheThread (param=0x10f91b0)
    at /home/kahrl/minetest/src/jthread/pthread/jthread.cpp:157
        jthread = 0x10f91b0
#4  0x00007ffff4fcf1da in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007ffff3bd6bbd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 6 (Thread 0x7fffe0654700 (LWP 6033)):
#0  0x00007ffff4fd344c in pthread_cond_wait () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007fffe27cfd63 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#2  0x00007fffe27cf5a7 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#3  0x00007ffff4fcf1da in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#4  0x00007ffff3bd6bbd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff7fac7c0 (LWP 6025)):
#0  0x00007ffff5455186 in sqlite3_finalize () from /usr/lib64/libsqlite3.so.0
No symbol table info available.
#1  0x00000000007b2aee in Database_SQLite3::~Database_SQLite3 (
    this=0x1177130, __in_chrg=<optimized out>)
    at /home/kahrl/minetest/src/database-sqlite3.cpp:304
        rc = 0

#2  0x00000000007b2c24 in Database_SQLite3::~Database_SQLite3 (
    this=0x1177130, __in_chrg=<optimized out>)
    at /home/kahrl/minetest/src/database-sqlite3.cpp:313
No locals.
#3  0x00000000008960fb in ServerMap::~ServerMap (this=0x117ad10, 
    __in_chrg=<optimized out>) at /home/kahrl/minetest/src/map.cpp:2209
No locals.
#4  0x000000000089621c in ServerMap::~ServerMap (this=0x117ad10, 
    __in_chrg=<optimized out>) at /home/kahrl/minetest/src/map.cpp:2222
No locals.
#5  0x000000000089be92 in Map::drop (this=0x117ad10)
    at /home/kahrl/minetest/src/map.h:161
No locals.
#6  0x00000000007d37d2 in ServerEnvironment::~ServerEnvironment (
    this=0x1377770, __in_chrg=<optimized out>)
    at /home/kahrl/minetest/src/environment.cpp:373
No locals.
#7  0x00000000007d3972 in ServerEnvironment::~ServerEnvironment (
    this=0x1377770, __in_chrg=<optimized out>)
    at /home/kahrl/minetest/src/environment.cpp:380
No locals.
#8  0x00000000009264f8 in Server::~Server (this=0x10f8f60, 
    __in_chrg=<optimized out>) at /home/kahrl/minetest/src/server.cpp:405
No locals.
#9  0x0000000000926a54 in Server::~Server (this=0x10f8f60, 
    __in_chrg=<optimized out>) at /home/kahrl/minetest/src/server.cpp:427
No locals.
#10 0x00000000007f6a1c in Game::~Game (this=0x7fffffffd140, 
    __in_chrg=<optimized out>) at /home/kahrl/minetest/src/game.cpp:1678
No locals.
#11 0x0000000000804463 in the_game (kill=0xe02210 <porting::g_killed>, 
    random_input=false, input=0x100e470, device=0xe3d9f0, 
    map_dir="/home/kahrl/minetest/bin/../worlds/bla", 
    playername="singleplayer", password="", address="", port=58792, 
    error_message=L"Access denied. Reason: Go away.", chat_backend=..., 
    gamespec=..., simple_singleplayer_mode=true)
    at /home/kahrl/minetest/src/game.cpp:4198
        game = {input = 0x100e470, client = 0x1503730, server = 0x10f8f60, 
          texture_src = 0x10e1810, shader_src = 0x11759a0, 
          itemdef_manager = 0x10b93e0, nodedef_manager = 0x10ab5b0, 
          soundfetcher = {<OnDemandSoundFetcher> = {
              _vptr.OnDemandSoundFetcher = 0xa58780 <vtable for GameOnDemandSoundFetcher+16>}, m_fetched = std::set with 0 elements}, sound = 0x10a9c20, 
          sound_is_dummy = false, soundmaker = 0x10dd6a0, 
          chat_backend = 0x7fffffffd5f0, current_formspec = 0x0, 
          eventmgr = 0x107be30, quicktune = 0x106e210, gui_chat_console = 
    0x0, draw_control = 0xe1bed0, camera = 0x0, clouds = 0x0, sky = 0x0, 
          local_inventory = 0x0, hud = 0x0, device = 0xe3d9f0, 
          driver = 0xfb3da0, smgr = 0x100b480, 
          kill = 0xe02210 <porting::g_killed>, 
          error_message = 0x7fffffffd540, gamedef = 0x1503740, 
          skybox = 0x109d888, random_input = false, 
          simple_singleplayer_mode = true, crack_animation_length = 0, 
          guitext = 0x10ab948, guitext2 = 0xffffffff, 
          guitext_info = 0x7ffff46b0418 <std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_S_empty_rep_storage+24>, 
          guitext_status = 0x7ffff769003a <irr::core::array<irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> >, irr::core::irrAllocator<irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> > > >::insert(irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> > const&, unsigned int)+858>, 
          guitext_chat = 0x7ffff46b03f8 <std::string::_Rep::_S_empty_rep_storage+24>, guitext_profiler = 0x7ffff746ed18, infotext = L"", statustext = L"", 
          keycache = {key = {{Key = irr::KEY_KEY_W, Char = 87 L'W', 
                m_name = "KEY_KEY_W"}, {Key = irr::KEY_KEY_S, 
                Char = 83 L'S', m_name = "KEY_KEY_S"}, {
                Key = irr::KEY_KEY_A, Char = 65 L'A', m_name = "KEY_KEY_A"}, 
              {Key = irr::KEY_KEY_D, Char = 68 L'D', m_name = "KEY_KEY_D"}, {
                Key = irr::KEY_SPACE, Char = 0 L'\000', 
                m_name = "KEY_SPACE"}, {Key = irr::KEY_KEY_E, 
                Char = 69 L'E', m_name = "KEY_KEY_E"}, {
                Key = irr::KEY_LSHIFT, Char = 0 L'\000', 
                m_name = "KEY_LSHIFT"}, {Key = irr::KEY_KEY_Q, 
                Char = 81 L'Q', m_name = "KEY_KEY_Q"}, {
                Key = irr::KEY_KEY_I, Char = 73 L'I', m_name = "KEY_KEY_I"}, 
              {Key = irr::KEY_KEY_T, Char = 84 L'T', m_name = "KEY_KEY_T"}, {
                Key = irr::KEY_KEY_CODES_COUNT, Char = 47 L'/', 
                m_name = "/"}, {Key = irr::KEY_F10, Char = 0 L'\000', 
                m_name = "KEY_F10"}, {Key = irr::KEY_KEY_K, Char = 75 L'K', 
                m_name = "KEY_KEY_K"}, {Key = irr::KEY_KEY_J, 
                Char = 74 L'J', m_name = "KEY_KEY_J"}, {
                Key = irr::KEY_KEY_H, Char = 72 L'H', m_name = "KEY_KEY_H"}, 
              {Key = irr::KEY_F12, Char = 0 L'\000', m_name = "KEY_F12"}, {
                Key = irr::KEY_F1, Char = 0 L'\000', m_name = "KEY_F1"}, {
                Key = irr::KEY_F2, Char = 0 L'\000', m_name = "KEY_F2"}, {
                Key = irr::KEY_F3, Char = 0 L'\000', m_name = "KEY_F3"}, {
                Key = irr::KEY_KEY_CODES_COUNT, Char = 110 L'n', 
                m_name = "n"}, {Key = irr::KEY_F5, Char = 0 L'\000', 
                m_name = "KEY_F5"}, {Key = irr::KEY_F6, Char = 0 L'\000', 
                m_name = "KEY_F6"}, {Key = irr::KEY_F7, Char = 0 L'\000', 
                m_name = "KEY_F7"}, {Key = irr::KEY_KEY_CODES_COUNT, 
                Char = 43 L'+', m_name = "+"}, {
                Key = irr::KEY_KEY_CODES_COUNT, Char = 45 L'-', 
                m_name = "-"}, {Key = irr::KEY_KEY_R, Char = 82 L'R', 
                m_name = "KEY_KEY_R"}, {Key = irr::KEY_END, 
                Char = 0 L'\000', m_name = "KEY_END"}, {Key = irr::KEY_HOME, 
                Char = 0 L'\000', m_name = "KEY_HOME"}, {
                Key = irr::KEY_PRIOR, Char = 0 L'\000', 
                m_name = "KEY_PRIOR"}, {Key = irr::KEY_NEXT, 
                Char = 0 L'\000', m_name = "KEY_NEXT"}, {
                Key = irr::KEY_KEY_P, Char = 80 L'P', 
                m_name = "KEY_KEY_P"}}}, profiler_interval = {
            m_accumulator = 0}, m_cache_doubletap_jump = false, 
          m_cache_enable_node_highlighting = false, 
          m_cache_enable_clouds = true, m_cache_enable_particles = true, 
          m_cache_enable_fog = true, 
          m_cache_mouse_sensitivity = 0.200000003, 
          m_repeat_right_click_time = 0.25}
        server_address = ""
#12 0x00000000008860e2 in ClientLauncher::run (this=0x7fffffffd8d0, 
    game_params=..., cmd_args=...) at /home/kahrl/minetest/src/main.cpp:1750
        game_has_run = true
        text = 0x1044e70 L"\x7273752f\x62696c2f\x6c2f3436\x73616269\x646e756f\x2e6f732e\x4f460032\x5f746c00\060"
        video_driver = 0xfb3da0
        __PRETTY_FUNCTION__ = "bool ClientLauncher::run(GameParams&, const Settings&)"
        retval = true
        kill = 0xe02210 <porting::g_killed>
        camera = 0x1044a00
        chat_backend = {m_console_buffer = {m_scrollback = 500, 
            m_unformatted = std::vector of length 0, capacity 0, m_cols = 0, 
            m_rows = 0, m_scroll = 0, 
            m_formatted = std::vector of length 0, capacity 0, 
            m_empty_formatted_line = {
              fragments = std::vector of length 0, capacity 0, 
              first = true}}, m_recent_buffer = {m_scrollback = 6, 
            m_unformatted = std::vector of length 0, capacity 0, m_cols = 0, 
            m_rows = 0, m_scroll = 0, 
            m_formatted = std::vector of length 0, capacity 0, 
            m_empty_formatted_line = {
              fragments = std::vector of length 0, capacity 0, 
              first = true}}, m_prompt = {m_prompt = L"]", m_line = L"", 
            m_history = std::vector of length 0, capacity 0, 
            m_history_index = 0, m_history_limit = 500, m_cols = 0, 
            m_view = 0, m_cursor = 0, m_nick_completion_start = 0, 
            m_nick_completion_end = 0}}
        error_message = L"Access denied. Reason: Go away."
        first_loop = false
#13 0x000000000087f160 in main (argc=1, argv=0x7fffffffdbc8)
    at /home/kahrl/minetest/src/main.cpp:866
        retval = 0
        cmd_args = {m_settings = std::map with 0 elements, 
          m_defaults = std::map with 0 elements, 
          m_callbacks = std::map with 0 elements, m_callbackMutex = {
            mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                __nusers = 0, __kind = 0, __spins = 0, __elision = 0, 
                __list = {__prev = 0x0, __next = 0x0}}, 
              __size = '\000' <repeats 39 times>, __align = 0}}, m_mutex = {
            mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                __nusers = 0, __kind = 0, __spins = 0, __elision = 0, 
                __list = {__prev = 0x0, __next = 0x0}}, 
              __size = '\000' <repeats 39 times>, __align = 0}}}
        cmd_args_ok = true
        __debug_stacker = {m_stack = 0xe0e9c0, m_overflowed = false}
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        game_params = {socket_port = 30000, 
          world_path = "/home/kahrl/minetest/bin/../worlds/world", 
          game_spec = {id = "minetest", 
            path = "/home/kahrl/minetest/bin/../games/minetest_game", 
            gamemods_path = "/home/kahrl/minetest/bin/../games/minetest_game/mods", addon_mods_paths = std::set with 1 elements = {
              [0] = "/home/kahrl/minetest/bin/../mods"}, name = "Minetest", 
            menuicon_path = "/home/kahrl/minetest/bin/../games/minetest_game/menu/icon.png"}, is_dedicated_server = false, log_level = 2}
        launcher = {list_video_modes = false, skip_main_menu = false, 
          use_freetype = true, random_input = false, address = "", 
          playername = "", password = "", device = 0xe3d9f0, 
          input = 0x100e470, receiver = 0xe3b520, skin = 0x1010990, font = 
    0x0, smgr = 0x100b480, gamespec = {id = "minetest", 
            path = "/home/kahrl/minetest/bin/../games/minetest_game", 
            gamemods_path = "/home/kahrl/minetest/bin/../games/minetest_game/mods", addon_mods_paths = std::set with 1 elements = {
              [0] = "/home/kahrl/minetest/bin/../mods"}, name = "Minetest", 
            menuicon_path = "/home/kahrl/minetest/bin/../games/minetest_game/menu/icon.png"}, worldspec = {
            path = "/home/kahrl/minetest/bin/../worlds/bla", name = "bla", 
            gameid = "minetest"}, simple_singleplayer_mode = true, 
          current_playername = "singleplayer", current_password = "", 
          current_address = "", current_port = 58792}
```

**Comment by kahrl** [comment]
Fixed by 4d15d631349005528e8578a5750ad9a1b8cefe39.
