### ISSUE TITLE
PcgRandom crashes the application.

### ISSUE THREAD

**Issue by 1Nick1Name** [minetest/minetest#3027]
See: https://forum.minetest.net/viewtopic.php?f=6&t=13010

**Comment by est31** [comment]
Code to reproduce:
```
print ("----- Test starts.")
local pcg = PcgRandom(1439211891)
print ("----- generated pcg.")
local value = pcg:next();
print ("----- Help me I am never printed!")
print ("----- value="..tostring(value)..".")
```
Backtrace:
```
#0  0x0000000000a4bd27 in PcgRandom::range (this=0x1a483b0, bound=0) at src/noise.cpp:106
        threshhold = 4134941175
        r = 32767
#1  0x0000000000a4be08 in PcgRandom::range (this=0x1a483b0, min=-2147483648, max=2147483647)
    at src/noise.cpp:122
        bound = 0
#2  0x00000000007bf026 in LuaPcgRandom::l_next (L=0x40000378) at src/script/lua_api/l_noise.cpp:514
        nolocktime = {m_profiler = 0xf89a80 <main_profiler>, m_name = "Scriptapi: unlockable time", m_timer = 0x1ec0ac0, 
          m_type = SPT_ADD}
        o = 0x1a483b0
        min = 2147483648
        max = 2147483647
#3  0x000000000077615e in script_exception_wrapper (L=0x40000378, f=0x7bef64 <LuaPcgRandom::l_next(lua_State*)>)
    at src/script/common/c_internal.cpp:63
```

**Comment by 1Nick1Name** [comment]
Might be a 32 bit problem. I use 64 bit.

**Comment by est31** [comment]
I think this is a blocker issue, because PcgRandom is completely broken. It may not be an essential feature, but as the bug is reproducible, it can be hopefully easily fixed.

**Comment by est31** [comment]
This problem exists since 3993093f51544d4eb44efb57c973e29107ea2f7a

**Comment by est31** [comment]
738fbc66d096575bb9a1694056ce2d627a70c03d
