### ISSUE TITLE
Httpfetch hang at shutdown from game to OS

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest#3526]
After an hour or so of gameplay on a multiplayer server in a direct exit to OS, this happened:

```
(gdb) info threads
  Id   Target Id         Frame 
* 2    Thread 0x7fa6cb2be700 (LWP 32425) "CurlFetch" 0x00007fa6fc69429d in __lll_lock_wait () from /lib64/libpthread.so.0
  1    Thread 0x7fa6ff8e98c0 (LWP 32387) "minetest" 0x00007fa6fc68d59d in pthread_join () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fa6fc69429d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fa6fc68e89d in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x000000000076b1a3 in Event::signal (this=0x7fff4523b8e8) at /home/celeron55/softat/minetest/src/threading/event.cpp:81
#3  0x00000000008a14d3 in CurlFetchThread::processRequest (this=<optimized out>, req=...) at /home/celeron55/softat/minetest/src/httpfetch.cpp:495
#4  0x00000000008a17cc in CurlFetchThread::waitForRequest (this=0x199b4c0, timeout=<optimized out>) at /home/celeron55/softat/minetest/src/httpfetch.cpp:550
#5  0x00000000008a0749 in CurlFetchThread::run (this=0x199b4c0) at /home/celeron55/softat/minetest/src/httpfetch.cpp:676
#6  0x000000000076b73a in Thread::threadProc (param=0x199b4c0) at /home/celeron55/softat/minetest/src/threading/thread.cpp:262
#7  0x00007fa6fc68c555 in start_thread () from /lib64/libpthread.so.0
#8  0x00007fa6fa92eb9d in clone () from /lib64/libc.so.6
(gdb) thread 1
[Switching to thread 1 (Thread 0x7fa6ff8e98c0 (LWP 32387))]
#0  0x00007fa6fc68d59d in pthread_join () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fa6fc68d59d in pthread_join () from /lib64/libpthread.so.0
#1  0x000000000076b7a7 in Thread::wait (this=0x199b4c0) at /home/celeron55/softat/minetest/src/threading/thread.cpp:184
#2  0x000000000089f381 in httpfetch_cleanup () at /home/celeron55/softat/minetest/src/httpfetch.cpp:721
#3  0x00000000008c4260 in main (argc=<optimized out>, argv=<optimized out>) at /home/celeron55/softat/minetest/src/main.cpp:244
(gdb) 
```

**Comment by rubenwardy** [comment]
Is this reproducable?
