### ISSUE TITLE
Android: add crash reporting

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3988]
There are many one star reviews in android and many of the one star review comments say "app crashes" or something. Would be nice if we got an overview over the situation by using a crash analytics solution. In order to avoid lock in to proprietary solutions like gapps, I suggest to use [ACRA](http://www.acra.ch/), an apache licensed crashlytics application.

Also, somebody would need to host the server side [acralyzer](https://github.com/ACRA/acralyzer) part.

Of course, we should add a setting to disable crashlytics reporting.

**Comment by rubenwardy** [comment]
Google play allows players to report crashes

**Comment by MoNTE48** [comment]
@est31, If you want, I can give you a few thousand crash log. 98% - libc.so error. :)

**Comment by sofar** [comment]
crashes in libc are probably due to libc calls from the application with invalid pointers or data, and are still highly useful if they show a backtrace :)

**Comment by MoNTE48** [comment]
There is a backtrace. I can give your logs, if hp will not do it. But most errors occur on Chinese devices that have missing components in firmware.

**Comment by nerzhul** [comment]
@est31 i have the crash reports:

java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1319)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1053)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2099)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
	at android.app.ActivityThread.access$600(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:4987)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1907]:   104 could not load needed library 'libiconv.so' for 'libminetest.so' (load_library[1109]: Library 'libiconv.so' not found)
	at java.lang.Runtime.loadLibrary(Runtime.java:370)
	at java.lang.System.loadLibrary(System.java:535)
	at net.minetest.minetest.MtNativeActivity.<clinit>(MtNativeActivity.java:94)
	... 15 more

One other

java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/asec/net.minetest.minetest-1/lib/libminetest.so" has unexpected e_machine: 40
	at java.lang.Runtime.loadLibrary(Runtime.java:364)
	at java.lang.System.loadLibrary(System.java:526)
	at net.minetest.minetest.MtNativeActivity.<clinit>(MtNativeActivity.java:94)
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1208)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2216)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
	at android.app.ActivityThread.access$800(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5257)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
	at dalvik.system.NativeStart.main(Native Method)


And last

java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1319)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1071)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
	at android.app.ActivityThread.access$700(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5279)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: load_library(linker.cpp:761): not a valid ELF executable: /data/app-lib/net.minetest.minetest-1/libminetest.so
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:535)
	at net.minetest.minetest.MtNativeActivity.<clinit>(MtNativeActivity.java:94)
	... 15 more


The main problem is the libiconv which wasn't called from the java part. We should provide it for Android without libiconv

**Comment by MoNTE48** [comment]
You probably know well enough to develop C++ apps for Android. This is not a problem Minetest or iconv. This is a problem that the changes introduced in the ROM manufacturer. Try to run Minetest on Xiaomi (any phone). You will receive an error sqlite. Therefore it is necessary to remove sqlite, too?
