### ISSUE TITLE
static initialization problem

### ISSUE THREAD

**Issue by YuGiOhJCJ** [minetest/minetest#4201]
Hello,

I have cross compiled Minetest 0.4.13 from Linux to Windows and it seems that there is a problem with static initialization because the program crashes on Windows with the following backtrace:

```
Z:\Documents and Settings\yugiohjcj\Desktop>gdb minetest
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from minetest...done.
(gdb) run
Starting program: Z:\Documents and Settings\yugiohjcj\Desktop\usr\i686-w64-mingw32
\games\minetest-0.4.13\bin\minetest.exe
[New Thread 2612.0xa3c]

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0x0076b747 in __static_initialization_and_destruction_0 (
    __initialize_p=1, __priority=65535)
    at /usr/i686-w64-mingw32/include/c++/5.3.0/iostream:74
#2  0x0076b79c in _GLOBAL__sub_I__ZN3irr3gui10CGUITTFont9c_libraryE ()
    at /tmp/build/minetest-0.4.13/src/cguittfont/CGUITTFont.cpp:1175
#3  0x0076c09a in __do_global_ctors () at crt/gccmain.c:44
#4  0x0076c0ec in __main () at crt/gccmain.c:58
#5  0x004013b6 in __tmainCRTStartup () at crt/crtexe.c:324
#6  0x757d1793 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
#7  0x776fc206 in ntdll!RtlCreateMemoryZone ()
   from C:\Windows\SYSTEM32\ntdll.dll
#8  0x776fc1df in ntdll!RtlCreateMemoryZone ()
   from C:\Windows\SYSTEM32\ntdll.dll
#9  0x00000000 in ?? ()
(gdb) quit
A debugging session is active.

        Inferior 1 [process 2612] will be killed.

Quit anyway? (y or n) y
```

I see some static variables in the src/cguittfont/CGUITTFont.cpp file [1].
My guess is that at runtime, some of these static variables could be not initialized in the good order and it could be related to a static initialization order fiasco [2].
Further information about my problem can be found in my forum topic [3].

[1] https://github.com/minetest/minetest/blob/d44fceac7e1237b00c6431ee1bb5805b602d0dcd/src/cguittfont/CGUITTFont.cpp#L59
[2] https://isocpp.org/wiki/faq/ctors#static-init-order
[3] https://forum.minetest.net/viewtopic.php?f=6&t=14256

**Comment by nerzhul** [comment]
Is this aways present ?

**Comment by YuGiOhJCJ** [comment]
Well, it is old now and I have not anymore the tools installed on my computer to cross compile Minetest and check if the problem is still present with the last Minetest version.
You can close this ticket.
