### ISSUE TITLE
segfault after startup when luaentities file too large (no crash while running)

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4316]
Hi there, i restarted my server today and ran into a segmentation fault.
It is triggered by the pipeworks mod as i found out.
@VanessaE [told me to create a new issue here](https://github.com/minetest-mods/pipeworks/issues/144).

```
2016-07-13 21:13:18: ACTION[Server]: Announcing to servers.minetest.net
[New Thread 0x7ffff1a41700 (LWP 21356)]
[New Thread 0x7ffff1240700 (LWP 21357)]
[Thread 0x7ffff1240700 (LWP 21357) exited]
2016-07-13 21:13:19: ACTION[Server]: IRC: Connected!

Thread 4 "Server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2242700 (LWP 21350)]
0x000000000077e12a in std::thread::get_id (this=0x40) at /usr/include/c++/6.1.1/thread:174
174         { return _M_id; }
(gdb) bt
#0  0x000000000077e12a in std::thread::get_id (this=0x40) at /usr/include/c++/6.1.1/thread:174
#1  0x000000000077e16e in Thread::getThreadId (this=0xd7d070) at /home/minetest/minetest/src/threading/thread.h:99
#2  0x000000000077e148 in Thread::isCurrentThread (this=0xd7d070) at /home/minetest/minetest/src/threading/thread.h:93
#3  0x000000000080be5b in EmergeManager::getCurrentMapgen (this=0xd7c9d0) at /home/minetest/minetest/src/emerge.cpp:178
#4  0x000000000086da50 in ServerMap::updateVManip (this=0xd99f40, pos=...) at /home/minetest/minetest/src/map.cpp:2743
#5  0x000000000081931a in ServerEnvironment::swapNode (this=0x304e6b0, p=..., n=...) at /home/minetest/minetest/src/environment.cpp:1120
#6  0x00000000007030e3 in ModApiEnvMod::l_swap_node (L=0x40000378) at /home/minetest/minetest/src/script/lua_api/l_env.cpp:196
#7  0x00000000006debcf in script_exception_wrapper (L=0x40000378, f=0x703040 <ModApiEnvMod::l_swap_node(lua_State*)>)
    at /home/minetest/minetest/src/script/common/c_internal.cpp:63
#8  0x00007ffff764e41c in ?? () from /usr/lib/libluajit-5.1.so.2
#9  0x00007ffff7693ba0 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
#10 0x00000000006f116d in ScriptApiNode::node_on_timer (this=0xd85928, p=..., node=..., dtime=3) at /home/minetest/minetest/src/script/cpp_api/s_node.cpp:210
#11 0x0000000000818c38 in ServerEnvironment::activateBlock (this=0x304e6b0, block=0x7fffe00226a0, additional_dtime=0) at /home/minetest/minetest/src/environment.cpp:1042
#12 0x000000000081a747 in ServerEnvironment::step (this=0x304e6b0, dtime=0.100000001) at /home/minetest/minetest/src/environment.cpp:1398
#13 0x00000000008f3e17 in Server::AsyncRunStep (this=0x7fffffffd3e0, initial_step=false) at /home/minetest/minetest/src/server.cpp:567
#14 0x00000000008f07d7 in ServerThread::run (this=0xd7c950) at /home/minetest/minetest/src/server.cpp:100
#15 0x000000000073dd1f in Thread::threadProc (param=0xd7c950) at /home/minetest/minetest/src/threading/thread.cpp:252
#16 0x000000000073e992 in std::_Bind_simple<void* (*(Thread*))(void*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xd94ca8) at /usr/include/c++/6.1.1/functional:1400
#17 0x000000000073e8e3 in std::_Bind_simple<void* (*(Thread*))(void*)>::operator()() (this=0xd94ca8) at /usr/include/c++/6.1.1/functional:1389
#18 0x000000000073e8c2 in std::thread::_State_impl<std::_Bind_simple<void* (*(Thread*))(void*)> >::_M_run() (this=0xd94ca0) at /usr/include/c++/6.1.1/thread:196
#19 0x00007ffff5ccda9f in std::execute_native_thread_routine (__p=0xd94ca0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#20 0x00007ffff6f94484 in start_thread () from /usr/lib/libpthread.so.0
#21 0x00007ffff543f6dd in clone () from /usr/lib/libc.so.6
```

Regards

**Comment by tchncs** [comment]
Update: Minetest is starting successfull without the luaentities file but i am not sure how dangerous this wooden hammer methos is so dont wanna back into production so far....

**Comment by tchncs** [comment]
Update: after talking to the people in the irc, i just renamed the file and made my server public again.

**Comment by paramat** [comment]
```#3  0x000000000080be5b in EmergeManager::getCurrentMapgen (this=0xd7c9d0) at /home/minetest/minetest/src/emerge.cpp:178```
Mapgen code was recenty changed by hmmmm, might be related to those changes.

**Comment by tchncs** [comment]
It happened again.
[here is the luaentities file](https://illuna-minetest.tk/luaentities.txt)

**Comment by sfan5** [comment]
same issue as #5169, closing.
