### ISSUE TITLE
Changing font settings with /set segfaults

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#4532]
I searched only a little for a pre-existing issue.  Typing `/set font_size 20` crashes minetest and there's no error in debug.txt.  I haven't tried any other settings, just that one string.

**Comment by paramat** [comment]
Seems some settings are sensitive to setting in-game.

**Comment by Wayward1** [comment]
I can reproduce this. Although, sometimes it doesn't crash for me, but gives this instead: http://imgur.com/a/Vu4eR

**Comment by HybridDog** [comment]
l tried it, it printed a long error message (Backtrace and memory map), tell me if l should show it. 
Then l executed $ export LC_ALL=C and tried it again but it only showed the error message "Segmentation fault"

**Comment by yamanq** [comment]
When debugging, I found that both the Server and Main thread run initFont with the same parameters and the segfault occurs on the second time initFont is run. I believe this is because the first thread to call initFont has not yet cached its results so that the other thread can get them. Ultimately, the crash occurs because FreeType is [not threadsafe](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_library). Here is the backtrace I get from running the command:

```
#0  0x00007ffff7139667 in ?? () from /usr/lib/libfreetype.so.6
#1  0x00007ffff7143516 in TT_RunIns () from /usr/lib/libfreetype.so.6
#2  0x00007ffff713b88e in ?? () from /usr/lib/libfreetype.so.6
#3  0x00007ffff71487b6 in ?? () from /usr/lib/libfreetype.so.6
#4  0x00007ffff714941f in ?? () from /usr/lib/libfreetype.so.6
#5  0x00007ffff712c8e4 in FT_Load_Glyph () from /usr/lib/libfreetype.so.6
#6  0x00005555559238df in irr::gui::SGUITTGlyph::preload (this=0x555559e62d20, char_index=13, face=0x555556f94540, 
    driver=0x555556ecaee0, font_size=15, loadFlags=4)
    at ~/minetest/src/irrlicht_changes/CGUITTFont.cpp:166
#7  0x00005555559269b2 in irr::gui::CGUITTFont::getGlyphIndexByChar (this=0x7fff64019e90, c=0 U'\000')
    at ~/minetest/src/irrlicht_changes/CGUITTFont.cpp:835
#8  0x0000555555924d20 in irr::gui::CGUITTFont::load (this=0x7fff64019e90, filename=..., size=15, antialias=true, 
    transparency=true) at ~/minetest/src/irrlicht_changes/CGUITTFont.cpp:405
#9  0x0000555555923c1d in irr::gui::CGUITTFont::createTTFont (env=0x5555569c6f00, filename=..., size=15, 
    antialias=true, transparency=true, shadow=0, shadow_alpha=0)
    at ~/minetest/src/irrlicht_changes/CGUITTFont.cpp:231
#10 0x00005555557822b7 in FontEngine::initFont (this=0x555556ee3060, spec=...)
    at ~/minetest/src/client/fontengine.cpp:320
#11 0x00005555557811e1 in FontEngine::getFont (this=0x555556ee3060, spec=...)
    at ~/minetest/src/client/fontengine.cpp:132
#12 0x00005555557813d4 in FontEngine::getLineHeight (this=0x555556ee3060, spec=...)
    at ~/minetest/src/client/fontengine.cpp:171
#13 0x00005555557b054a in FontEngine::getLineHeight (this=0x555556ee3060, font_size=4294967295, mode=FM_Unspecified)
    at ~/minetest/src/client/fontengine.h:121
#14 0x00005555557aefe2 in GameUI::setChatText (this=0x5555571b5170, chat_text=..., recent_chat_count=2)
    at ~/minetest/src/client/gameui.cpp:229
#15 0x000055555578feb6 in Game::updateChat (this=0x7fffffffe0b0, dtime=0.0170000009, screensize=...)
    at ~/minetest/src/client/game.cpp:2870
#16 0x0000555555795d09 in Game::updateFrame (this=0x7fffffffe0b0, graph=0x7fffffffdf80, stats=0x7fffffffdf40, 
    dtime=0.0170000009, cam=...) at ~/minetest/src/client/game.cpp:3795
#17 0x000055555578655f in Game::run (this=0x7fffffffe0b0) at ~/minetest/src/client/game.cpp:1138
#18 0x0000555555799ec3 in the_game (kill=0x55555606f740 <porting::g_killed>, input=0x555557039fe0, start_data=..., 
    error_message="", chat_backend=..., reconnect_requested=0x7fffffffe3ec)
    at ~/minetest/src/client/game.cpp:4253
#19 0x0000555555733b11 in ClientLauncher::run (this=0x7fffffffe710, start_data=..., cmd_args=...)
    at ~/minetest/src/client/clientlauncher.cpp:273
#20 0x0000555555ba4121 in main (argc=1, argv=0x7fffffffeba8) at ~/minetest/src/main.cpp:221

```

I made this [patch](https://github.com/yamanq/minetest/commits/yamanq/setfont) that prevents the crash from happening but this still results in the strange screenshot posted above. If FontEngine::readSettings() is called on the client thread, for example by binding the punch action to it, the font is loaded on the client correctly.

The smallest function I could come up with to fix the rendering if run on the client thread is just rewriting the cache with a new font and then updating the skin:
```
void FontEngine::testFunction() {
	FontSpec spec{m_default_size[m_currentMode], m_currentMode, false, false};
	gui::IGUIFont *font = initFont(spec);
	m_font_cache[spec.getHash()][spec.size] = font;
	m_env->getSkin()->setFont(font);
}

```

Do you have any suggestions on how to proceed from here?
