### ISSUE TITLE
Crash on certain map save after transfer from singlenode to mapgenv7 (possible wrong usage of minetest)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4885]
**Update: This can be wrong usage of minetest and me to blame. Because read post by est31 below.**

I've had "Just Test" server save (by local map saving) that I made long time ago, it worked, but today I decided to move it from singlenode type to mapgenv7 type (as it should), created world with that seed to generate map_meta file, copied it into just test world save, started it and did fly around around its borders to generate new parts and it kinda did, but at some position I started to have CTD, reproducible ones on minetest 2886f0c.

Crashy world after 1st crash: [Just Test.zip](https://github.com/minetest/minetest/files/644157/Just.Test.zip)
To reproduce: load that world and fly along the houses were lies saved world edge.

**Backtrace:** http://pastebin.com/raw/jykdDxpG 
I did not saved it all, it was >2000 lines of basically the same thing. Something related to lighting?

**Comment by est31** [comment]
From reading this this appears like wrong usage. singlenode mapgen is the only mapgen that is made to work with not fully generated mapchunks. With mapgenv7 you will run into issues.

**Comment by Fixer-007** [comment]
Probably, if someone wants to poke the issue, you are fine to do :) There are other ways to workaround the problem.

**Comment by twoelk** [comment]
singlenode node is indeed used for many purposes. it is usefull and even essential for some tasks, there for I would consider it vital that content generated or created with singlenode activated can easily be merged with any other "real" mapgen. 
but as singlenode actually creates more or less "nothing" or rather worlds filled with "air" this may be a hint that starting a mapgen7 map with foreign content, be it created while using singlenode or maybe content from some other source, is prone to crashing, which i would consider a real problem.

**Comment by rubenwardy** [comment]
It should gracefully crash. It shouldn't be possible for a user to cause a segfault/ungraceful crash

**Comment by est31** [comment]
oh right, that's correct. Its a bug.

**Comment by paramat** [comment]
```
Thread 17 (Thread 2588.0xca8):
#0  0x000000000079739b in VoxelArea::index (this=0x19402af8, x=-143, y=9, z=102)
    at /media/sf_Exchange/minetest/build/minetest/src/voxel.h:279
        em = {X = 0, Y = 0, Z = 0}
        off = {X = 0, Y = 0, Z = 0}
        i = 0
#1  0x000000000079735f in VoxelArea::index (this=0x19402af8, p=...) at /media/sf_Exchange/minetest/build/minetest/src/voxel.h:287
No locals.
#2  0x00000000005f1e08 in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=92 '\\')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:425
        vi = 65393
        n = @0xf2941b0: {param0 = 65393, param1 = 9 '\t', param2 = 0 '\000'}
        light_day = 0 '\000'
        light_night = 0 '\000'
```
param0 = 65393 seems suspicious, same as vi too. Can you go to x=-143, y=9, z=102) and see what's there?

**Comment by Fixer-007** [comment]
https://i.imgur.com/g6F1EKk.png it is air? behind me is edge of the saved world 1 block away.

**Comment by paramat** [comment]
Relevant part of backtrace, hundreds of entries like this:
```
Thread 17 (Thread 2588.0xca8):
#0  0x000000000079739b in VoxelArea::index (this=0x19402af8, x=-143, y=9, z=102)
    at /media/sf_Exchange/minetest/build/minetest/src/voxel.h:279
        em = {X = 0, Y = 0, Z = 0}
        off = {X = 0, Y = 0, Z = 0}
        i = 0
#1  0x000000000079735f in VoxelArea::index (this=0x19402af8, p=...) at /media/sf_Exchange/minetest/build/minetest/src/voxel.h:287
No locals.
#2  0x00000000005f1e08 in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=92 '\\')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:425
        vi = 65393
        n = @0xf2941b0: {param0 = 65393, param1 = 9 '\t', param2 = 0 '\000'}
        light_day = 0 '\000'
        light_night = 0 '\000'
#3  0x00000000005f1fb0 in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=92 '\\')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:452
        vi = 871985
        n = @0x17943904: {param0 = 126, param1 = 92 '\\', param2 = 0 '\000'}
        light_day = 12 '\f'
        light_night = 80 'P'
#4  0x00000000005f206a in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=109 'm')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:454
        vi = 871984
        n = @0x17943900: {param0 = 126, param1 = 109 'm', param2 = 0 '\000'}
        light_day = 13 '\r'
        light_night = 96 '`'
#5  0x00000000005f1fb0 in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=126 '~')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:452
        vi = 859440
        n = @0x17937500: {param0 = 126, param1 = 126 '~', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 80 'P'
#6  0x00000000005f206a in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=111 'o')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:454
        vi = 859439
        n = @0x179374fc: {param0 = 126, param1 = 111 'o', param2 = 0 '\000'}
        light_day = 12 '\f'
        light_night = 96 '`'
#7  0x00000000005f2184 in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=125 '}')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:457
        vi = 859440
        n = @0x17937500: {param0 = 126, param1 = 126 '~', param2 = 0 '\000'}
        light_day = 13 '\r'
        light_night = 112 'p'
#8  0x00000000005f200e in Mapgen::lightSpread (this=0xd00b770, a=..., p=..., light=142 'Ћ')
    at /media/sf_Exchange/minetest/build/minetest/src/mapgen.cpp:453
        vi = 859328
        n = @0x17937340: {param0 = 126, param1 = 142 'Ћ', param2 = 0 '\000'}
        light_day = 14 '\016'
        light_night = 0 '\000'
```

**Comment by paramat** [comment]
At that point in history:
L425
```
	u32 vi = vm->m_area.index(p);
```
L452 to L457
```
	lightSpread(a, p + v3s16(0, 0, 1), light);
	lightSpread(a, p + v3s16(0, 1, 0), light);
	lightSpread(a, p + v3s16(1, 0, 0), light);
	lightSpread(a, p - v3s16(0, 0, 1), light);
	lightSpread(a, p - v3s16(0, 1, 0), light);
	lightSpread(a, p - v3s16(1, 0, 0), light);
}
```

**Comment by paramat** [comment]
Probably wrong usage, see above.
