### ISSUE TITLE
Segmentation Violation (Linux) with latest Minetest

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#5723]
This was while playing "Legend Of Minetest" with my son. Doesn't happen all the time, but often enough to be annoying.

Didn't compile debug symbols when this happened. Just recording it here for later.
Perhaps somebody has an idea, seems there were a bunch of changes in this area lately.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc5ecec0336 in strlen () from /lib64/libc.so.6
#1  0x000000000050d84c in read_schematic_replacements(lua_State*, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*) ()
#2  0x00000000005127b0 in ModApiMapgen::l_place_schematic(lua_State*) ()
#3  0x00000000004d1266 in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#4  0x00007fc5ef16fcfc in lj_BC_FUNCCW () from /lib64/libluajit-5.1.so.2
#5  0x00007fc5ef1b5ad0 in lua_pcall () from /lib64/libluajit-5.1.so.2
#6  0x00000000004d7c73 in ScriptApiBase::runCallbacksRaw(int, RunCallbacksMode, char const*) ()
#7  0x00000000004da727 in ScriptApiEnv::environment_OnGenerated(irr::core::vector3d<short>, irr::core::vector3d<short>, unsigned int) ()
#8  0x0000000000632417 in EmergeThread::finishGen(irr::core::vector3d<short>, BlockMakeData*, std::map<irr::core::vector3d<short>, MapBlock*, std::less<irr::core::vector3d<short> >, std::allocator<std::pair<irr::core::vector3d<short> const, MapBlock*> > >*) ()
#9  0x0000000000633692 in EmergeThread::run() ()
#10 0x0000000000538d89 in Thread::threadProc(void*) ()
#11 0x00007fc5ed7d55cf in ?? () from /lib64/libstdc++.so.6
```

**Comment by paramat** [comment]
A mod is placing a schematic and something may be wrong with the 'replacements' specified for a schematic, if you can link to the schematic-placing code that would be helpful.

**Comment by nerzhul** [comment]
@lhofhansl can you provide us debugging symbols backtrace ?

**Comment by nerzhul** [comment]
looking at the decoding function, there is no type check inside it, it can crash if you read a string and value is not a string

**Comment by nerzhul** [comment]
can you test #5726 patch @lhofhansl ? it will permit to catch the mod error

**Comment by ShadowNinja** [comment]
c07c642ab091b7250ecdc5defee1fec26ba73dc4

**Comment by lhofhansl** [comment]
Awesome. Got the culprit.

```
2017-05-08 19:22:16: ERROR[Main]: ServerError: AsyncErr: Lua: finishGenRuntime error from mod 'hyrule_mapgen' in callback environment_OnGenerated(): schematics: replace_from field is not a string
2017-05-08 19:22:16: ERROR[Main]: stack traceback:
2017-05-08 19:22:16: ERROR[Main]:       [C]: in function 'place_schematic'
2017-05-08 19:22:16: ERROR[Main]:       ...est/games/LegendofMinetest/mods/hyrule_mapgen/mapgen.lua:1861: in function <...est/games/LegendofMinetest/mods/hyrule_mapgen/mapgen.lua:1845>
2017-05-08 19:22:16: ERROR[Main]:       /opt/minetest/share/minetest/builtin/game/register.lua:412: in function </opt/minetest/share/minetest/builtin/game/register.lua:392>
```

**Comment by nerzhul** [comment]
@lhofhansl nice, now you can fix your mod :)
