### ISSUE TITLE
Client crash when digging protected area

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5898]
Bug was found on "Jungle" server that is stable 0.4.15, digging in protected area (by protector_redo, areas mod is also loaded but not used in that place) causes client crash (0.4.16 and probably older) with this backtrace:
```
[New Thread 0x7fffe808f700 (LWP 8198)]

Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x0000000000b1b464 in ToolCapabilities::operator= (this=0x7fffffffc760) at *******/minetest/src/tool.h:56
56	struct ToolCapabilities
(gdb) bt
#0  0x0000000000b1b464 in ToolCapabilities::operator= (this=0x7fffffffc760) at *******/minetest/src/tool.h:56
#1  0x0000000000b0a6bf in Game::processPlayerInteraction (this=0x7fffffffcd70, dtime=0.0209999997, show_hud=true, show_debug=false)
    at *******/minetest/src/game.cpp:3601
#2  0x0000000000b0013d in Game::run (this=0x7fffffffcd70) at *******/minetest/src/game.cpp:1687
#3  0x0000000000b1256e in the_game (kill=0x1264820 <porting::g_killed>, random_input=false, input=0x20f44b0, device=0x1bca110, 
    map_dir="*******/minetest/bin/../worlds/world", playername="JungleMan21", password="lol, did you really think I don't censor my password? :P", address="78.47.93.144", port=39155, error_message="", 
    chat_backend=..., reconnect_requested=0x7fffffffd89f, gamespec=..., simple_singleplayer_mode=false) at *******/minetest/src/game.cpp:4675
#4  0x00000000008a2ca8 in ClientLauncher::run (this=0x7fffffffdd80, game_params=..., cmd_args=...)
    at *******/minetest/src/client/clientlauncher.cpp:241
#5  0x0000000000bb4b0d in main (argc=1, argv=0x7fffffffe528) at *******/minetest/src/main.cpp:212
```
Discussion here: http://irc.minetest.net/minetest-dev/2017-06-03#i_4957060
```
ShadowNinja: JungleMan21: Can you run "bt full" and see what hand_def.tool_capabilities is?
...
JungleMan21: ShadowBot: 0x0
```

Bug was reproduced by me and other players. I was not able to reproduce it on Hometown (protector_redo), Amhi (protector_redo, areas), Vanessa Dreamb Survival (areas), LibertyLand (landrush).

Proposed fix by @ShadowNinja https://github.com/minetest/minetest/pull/5899 that fixes the crash for me.

Thanks to JungleMan21 for reporting

**Comment by Fixer-007** [comment]
Merged https://github.com/minetest/minetest/pull/5899
