### ISSUE TITLE
Clang failure during Travis build checks

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7276]
Not sure if MT's fault but it looks like it.
EDIT: Probably not.
```
Traceback (most recent call last):
  File "./util/travis/run-clang-tidy.py", line 271, in <module>
    main()
  File "./util/travis/run-clang-tidy.py", line 209, in main
    database = json.load(open(os.path.join(build_path, db_path)))
IOError: [Errno 2] No such file or directory: 'cmakebuild/compile_commands.json'
Clang tidy returned 1
```

**Comment by nerzhul** [comment]
which branch ? seems tidy was run whereas cmake wasn't run with compile commands output

**Comment by paramat** [comment]
Commit was either 534971ccd0a2b0bf4bfb6c7345c457e92f252fcc or 06dd7c051c7f1a6f5cc5dff0ed5b60a707422ea4 so very recent.
