### ISSUE TITLE
Segfault with Disabled freetype fonts

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#7611]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0-dev-4b36a39d
```

##### OS / Hardware
Operating system: ArchLinux
CPU: Intel Core I7-2600K

##### Summary
I accidentally selected "Disable freetype fonts" in menu and after reloading the game, it segfaults. If this is because "everyone should use freetype", it's probably better to remove this setting :P

##### Minetest.conf
```
freetype = false
```

##### GDB Log + Backtrace
```
(gdb) run
Starting program: /home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/minetest 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
2018-08-03 14:17:03: ERROR[Main]: Subgame specified in default_game [minetest] is invalid.
[New Thread 0x7fffeed86700 (LWP 29169)]
[Thread 0x7fffeed86700 (LWP 29169) exited]
[New Thread 0x7fffeed86700 (LWP 29171)]
[New Thread 0x7fffeed86700 (LWP 29172)]
[Thread 0x7fffeed86700 (LWP 29171) exited]
AL lib: (EE) SetChannelMap: Failed to match front-center channel (2) in channel map
[New Thread 0x7fffec8b8700 (LWP 29173)]
[New Thread 0x7fffca1ef700 (LWP 29174)]
[New Thread 0x7fffc97dc700 (LWP 29175)]
[New Thread 0x7fffc8fdb700 (LWP 29176)]
[New Thread 0x7fffbbfff700 (LWP 29177)]
[New Thread 0x7fffb37fe700 (LWP 29178)]
[New Thread 0x7fffbb7fe700 (LWP 29179)]
[New Thread 0x7fffbaffd700 (LWP 29180)]
[New Thread 0x7fffba7fc700 (LWP 29181)]
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Not trying to open "/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf" which seems to be a truetype font.
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Default font file: 
2018-08-03 14:17:03: ERROR[Main]: 	"/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf"
2018-08-03 14:17:03: ERROR[Main]: 	required for current screen configuration was not found or was invalid file format.
2018-08-03 14:17:03: ERROR[Main]: 	Using irrlicht default font.
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Not trying to open "/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf" which seems to be a truetype font.
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Not trying to open "/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf" which seems to be a truetype font.
[New Thread 0x7fffb9ffb700 (LWP 29182)]
[New Thread 0x7fffb97fa700 (LWP 29183)]
[New Thread 0x7fffb8ff9700 (LWP 29184)]
[New Thread 0x7fffb3fff700 (LWP 29185)]
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Not trying to open "/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf" which seems to be a truetype font.
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Not trying to open "/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf" which seems to be a truetype font.
2018-08-03 14:17:03: ERROR[Main]: FontEngine: Not trying to open "/home/thedragonix/Experiments/Игры-и-аддоны/minetest/bin/../fonts/Arimo-Regular.ttf" which seems to be a truetype font.

Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x00005555557833e8 in GUIFormSpecMenu::regenerateGui(irr::core::vector2d<unsigned int>) ()
(gdb) backtrace
#0  0x00005555557833e8 in GUIFormSpecMenu::regenerateGui(irr::core::vector2d<unsigned int>) ()
#1  0x000055555574bc69 in GUIModalMenu::draw() ()
#2  0x00007ffff7812a72 in irr::gui::CGUIStaticText::draw() () from /usr/lib/libIrrlicht.so.1.8
#3  0x00007ffff77c74ba in irr::gui::CGUIEnvironment::drawAll() () from /usr/lib/libIrrlicht.so.1.8
#4  0x0000555555763e6f in GUIEngine::run() ()
#5  0x00005555557648af in GUIEngine::GUIEngine(JoystickController*, irr::gui::IGUIElement*, IMenuManager*, MainMenuData*, bool&) ()
#6  0x00005555556c7d95 in ClientLauncher::main_menu(MainMenuData*) ()
#7  0x00005555556c8873 in ClientLauncher::launch_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, GameParams&, Settings const&) ()
#8  0x00005555556ca885 in ClientLauncher::run(GameParams&, Settings const&) ()
#9  0x00005555556c15f4 in main ()
```

##### Steps to reproduce
1. Set minetest.conf as above
2. Launch MT and observe segfault

**Comment by SmallJoker** [comment]
Servers do not need freetype, but we could consider to make it a hard dependency for clients.

**Comment by SmallJoker** [comment]
Update: There's now no longer a segfault, but an error in the terminal output + log file.

**Comment by rubenwardy** [comment]
> Update: There's now no longer a segfault, but an error in the terminal output + log file.

Should this be closed?
