### ISSUE TITLE
Bugs in stujones11's Android  5.0.0-dev builds

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7994]
See https://github.com/minetest/minetest/issues/7965#issuecomment-447694723 onwards.

**Comment by Fixer-007** [comment]
Blue screen and crash on startup on kitkat 4.4.2 with Minetest-05f3dbf

**Comment by nerzhul** [comment]
are we in a feature freeze phasis ? can we start it ? it seems we collect many problems to do a release but we don't statuate on it

**Comment by stujones11** [comment]
@Fixer-007 Did you try any of the my previous builds, is it only the 05f3dbf version?

**Comment by Fixer-007** [comment]
I've removed Minetest directory after trying to run your version without success. I will try some of your older versions later.

**Comment by stujones11** [comment]
> I've removed Minetest directory after trying to run your version without success.

Does the attempted launch produce a `debug.txt`? if so then please share it, a backtrace would also be very helpful.

**Comment by stujones11** [comment]
I finally managed to get my old android 4.1 tablet working and can now confirm this. _It involved soldering it directly to a 5v supply since charger socket was damaged_

The problem would appear to be with `libc++_shared.so` as we had previously suspected only it does to make sense that it should work for @VanessaE with android 4.3.
```
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libc++_shared.so" needed by "libiconv.so"; caused by load_library(linker.cpp:745): library "libc++_shared.so" not found
```
I think we may need to be including this lib like we do for the other shared libs, however, I won't be able to do much more until nearer the weekend, and holidays \o/

**Comment by Fixer-007** [comment]
This error on 4.4.2 with https://www.dropbox.com/s/a74e4r3so4t90ab/Minetest-612c172.apk?dl=0 that stu posted in https://github.com/minetest/minetest/pull/8003

```
E/AndroidRuntime(15502): FATAL EXCEPTION: main
E/AndroidRuntime(15502): Process: net.minetest.minetest, PID: 15502
E/AndroidRuntime(15502): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.minetest.minetest/net.minetest.minetest.MinetestAssetCopy}: android.view.InflateException: Binary XML file line #7: Error inflating class android.widget.ProgressBar
E/AndroidRuntime(15502): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
E/AndroidRuntime(15502): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
E/AndroidRuntime(15502): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(15502): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(15502): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(15502): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(15502): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(15502): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15502): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15502): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
E/AndroidRuntime(15502): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
E/AndroidRuntime(15502): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(15502): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(15502): Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.widget.ProgressBar
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime(15502): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(15502): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime(15502): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.inflate(Native Method)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime(15502): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:314)
E/AndroidRuntime(15502): 	at android.app.Activity.setContentView(Activity.java:1944)
E/AndroidRuntime(15502): 	at net.minetest.minetest.MinetestAssetCopy.onCreate(MinetestAssetCopy.java:33)
E/AndroidRuntime(15502): 	at android.app.Activity.performCreate(Activity.java:5264)
E/AndroidRuntime(15502): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
E/AndroidRuntime(15502): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
E/AndroidRuntime(15502): 	... 12 more
E/AndroidRuntime(15502): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(15502): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(15502): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(15502): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime(15502): 	... 28 more
E/AndroidRuntime(15502): Caused by: java.lang.NumberFormatException: Invalid int: "res/drawable/bg.xml"
E/AndroidRuntime(15502): 	at java.lang.Integer.invalidInt(Integer.java:137)
E/AndroidRuntime(15502): 	at java.lang.Integer.parse(Integer.java:374)
E/AndroidRuntime(15502): 	at java.lang.Integer.parseInt(Integer.java:365)
E/AndroidRuntime(15502): 	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
E/AndroidRuntime(15502): 	at android.content.res.TypedArray.getInt(TypedArray.java:260)
E/AndroidRuntime(15502): 	at android.content.res.XResources$XTypedArray.getInt(XResources.java:1002)
E/AndroidRuntime(15502): 	at android.view.animation.Animation.<init>(Animation.java:246)
E/AndroidRuntime(15502): 	at android.view.animation.AnimationSet.<init>(AnimationSet.java:81)
E/AndroidRuntime(15502): 	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:118)
E/AndroidRuntime(15502): 	at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:96)
E/AndroidRuntime(15502): 	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:77)
E/AndroidRuntime(15502): 	at android.widget.ProgressBar.<init>(ProgressBar.java:331)
E/AndroidRuntime(15502): 	at android.widget.ProgressBar.<init>(ProgressBar.java:262)
E/AndroidRuntime(15502): 	at android.widget.ProgressBar.<init>(ProgressBar.java:258)
E/AndroidRuntime(15502): 	... 31 more 
```

**Comment by stujones11** [comment]
@Fixer-007 Thanks, it looks like the error is with this line:
https://github.com/minetest/minetest/blob/d994f7ca5f75431da8e17fd6762209c404d89482/build/android/src/main/res/values-v21/styles.xml#L7
Unfortunately, I don't know much about the java side but from what I can find on stack-overflow it seems that `android:background` should be an integer value and that we should use `android:windowBackground` instead. However, this was only recently added/modified by f70f7875e2a2e49f80470832ae97e73f171d6460

Maybe @MoNTE48 can comment?

**Comment by MoNTE48** [comment]
@stujones11 No. Problem here
https://github.com/minetest/minetest/blob/f70f7875e2a2e49f80470832ae97e73f171d6460/build/android/src/main/res/drawable/bg.xml

**Comment by stujones11** [comment]
@MoNTE48 Thanks, any idea how to fix this? Sorry if I am missing something obvious.

**Comment by MoNTE48** [comment]
So far, not one :) I asked a friend, and await his answer. I do not know why this code does not work on 4.4

**Comment by stujones11** [comment]
Are you sure it is not this? https://stackoverflow.com/questions/21273553/android-custom-background-causing-number-format-exception-with-list-adapter

@Fixer-007 I had already made a build with this change if you care to try it. [Minetest-java-fix.apk](https://www.dropbox.com/s/8d8ghg38xx03oj0/Minetest-java-fix.apk?dl=0)

**Comment by MoNTE48** [comment]
Thank! I did not have the opportunity to search on the Internet, because I'm on the road. Add this fix to your PR! (It is very difficult to monitor the code support by different versions of Android. AS should have told me that I cannot use this method on older versions. But I didn’t do it.)
Sorry everyone! :(

**Comment by stujones11** [comment]
@MoNTE48 No problem, supporting multiple android versions is not an easy task. I will add that fix to my existing PR as soon as I get confirmation from @Fixer-007 that it actually works.

**Comment by Fixer-007** [comment]
It works!

**Comment by stujones11** [comment]
Great, now the only remaining issue I can see is: Crashes with no reason while in content screen

I can confirm that it is quite slow, especially on my oldest device but I have not been able to reproduce a crash. Without any more information, my best guess would be an OOM error.

**Comment by Fixer-007** [comment]
>Crashes with no reason while in content screen

Yeah, noticed that too, while scrolling pages, it does crash if you try to go singleplayer after browsing it, but it maybe my low mem issue (only few hundred mb free at most).

Another thing is that bottom black bar with left-home-apps does not hide sometimes and slightly obscures bottom part of hudbar.

**Comment by stujones11** [comment]
> Another thing is that bottom black bar with left-home-apps does not hide sometimes

Sorry, I have no idea about that but the navbar on my 4.2.1 device does not seem to auto-hide either. However, mine does have an actual hide button, looks like a down-pointing chevron.

**Comment by rubenwardy** [comment]
Here's a logcat from the CDB crash:

```
   : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:30.797 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:31.110 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:31.400 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:31.685 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:31.977 26418-26451/? I/chatty: uid=10341(u0_a341) MinetestNativeT identical 1 line
2018-12-21 20:30:32.270 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:32.562 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:32.855 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:33.141 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:33.434 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:34.022 26418-26451/? I/chatty: uid=10341(u0_a341) MinetestNativeT identical 2 lines
2018-12-21 20:30:34.311 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:34.605 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:34.844 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:35.114 26418-26451/? I/Irrlicht: LOAD PNG: not really a png
    : /sdcard/Minetest/tmp//MT_6723/game-Wuzzy-tutorial_game.png
2018-12-21 20:30:35.932 3667-4286/? I/WindowManager: WIN DEATH: Window{c2a7cdf u0 net.minetest.minetest/net.minetest.minetest.MtNativeActivity}
2018-12-21 20:30:35.955 3667-4444/? I/ActivityManager: Process net.minetest.minetest (pid 26418) has died: fore TOP (696,141)
2018-12-21 20:30:36.008 3667-3687/? D/GameManagerService: onProcessDied(), pid = 26418, uid = 10341, pkgName : net.minetest.minetest
2018-12-21 20:30:36.013 3667-4444/? W/ActivityManager: Force removing ActivityRecord{330196e u0 net.minetest.minetest/.MtNativeActivity t14879}: app died, no saved state
2018-12-21 20:30:36.102 3667-4286/? I/WindowManager: Destroying surface Surface(name=net.minetest.minetest/net.minetest.minetest.MtNativeActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2501 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:985 com.android.server.wm.WindowState.removeImmediately:2404 com.android.server.wm.WindowState.removeIfPossible:2606 com.android.server.wm.WindowState.-wrap1:0 com.android.server.wm.WindowState$DeathRecipient.binderDied:3151 android.os.BinderProxy.sendDeathNotice:841 <bottom of call stack> 
2018-12-21 20:30:36.108 3207-3229/? I/SurfaceFlinger: id=111 Removed net.minetest.minetest/net.minetest.minetest.MtNativeActivity#0 (1/4)
2018-12-21 20:30:36.114 3207-3229/? I/SurfaceFlinger: id=111 Removed net.minetest.minetest/net.minetest.minetest.MtNativeActivity#0 (-2/4)
2018-12-21 20:30:36.122 3207-3207/? I/Layer: id=111 onRemoved net.minetest.minetest/net.minetest.minetest.MtNativeActivity#0 
2018-12-21 20:30:36.203 3667-4444/? W/MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{a47a8e9d0 #14879 A=net.minetest.minetest U=0 StackId=1 sz=0}, rootActivity=null
2018-12-21 20:30:36.837 3667-3953/? D/GameManagerService: notifyResumePause(). pkg: net.minetest.minetest, type: 1, isMinimized: false, isTunableApp: false
2018-12-21 20:30:36.837 3667-3953/? D/GameManagerService:   notifyResumePause(). before send intent to GameTools. type:1, pkgName:net.minetest.minetest, minimized:false
2018-12-21 20:30:37.079 28905-29002/? D/GOS:GameIntentService: PROCESS_DIED, got process died signal, pkgName : net.minetest.minetest, pid : 26418, uid : 10341
2018-12-21 20:30:37.255 28905-29002/? D/GOS:PkgData: PkgData(), pkgName: net.minetest.minetest
2018-12-21 20:30:37.255 28905-29002/? D/GOS:PkgData: setCustomFeatureFlag, pkgName: net.minetest.minetest, old featureFlag: 346781844236309267, new featureFlag: 346781844236309267
2018-12-21 20:30:37.450 28905-29002/? D/GOS:ServiceManager: onGamePause. : net.minetest.minetest
2018-12-21 20:30:37.451 28905-29002/? D/GOS:PkgData: PkgData(), pkgName: net.minetest.minetest
2018-12-21 20:30:37.452 28905-29002/? D/GOS:PkgData: setCustomFeatureFlag, pkgName: net.minetest.minetest, old featureFlag: 346781844236309267, new featureFlag: 346781844236309267
2018-12-21 20:30:37.469 28905-29002/? D/GOS:VolumeControl: onPause. net.minetest.minetest
2018-12-21 20:30:37.473 28905-29002/? D/GOS:TouchBoost: onPause. net.minetest.minetest
2018-12-21 20:30:37.474 3667-5488/? D/PackageManager: getComponentMetadataForIconTray : net.minetest.minetest.MainActivity does not exist in mServices
2018-12-21 20:30:37.474 3667-5488/? D/PackageManager: getComponentMetadataForIconTray : net.minetest.minetest.MainActivity does not exist in mProviders
2018-12-21 20:30:37.474 3667-5488/? D/PackageManager: getComponentMetadataForIconTray : net.minetest.minetest.MainActivity does not exist in mReceivers
2018-12-21 20:30:37.474 4137-25848/? D/ApplicationPackageManager: updateItemMetaDataForFixedIconScale: package: net.minetest.minetest
2018-12-21 20:30:37.474 28942-29121/? I/GameTools: GameToolsIntentService : TYPE : 1 PKGNAME : net.minetest.minetest isGameApp : false
2018-12-21 20:30:37.475 28942-29121/? I/GameTools: GameToolsIntentService : startToolsService 1, net.minetest.minetest
2018-12-21 20:30:37.475 3667-4211/? D/PackageManager: getSelectedMetaData : packageName(net.minetest.minetest) or Metadata strings {[Ljava.lang.String;@f132fcb}
2018-12-21 20:30:37.478 28905-29002/? D/GOS:MicroGameBenchFeature: onPause. net.minetest.minetest, allowed: true
2018-12-21 20:30:37.484 4137-25848/? I/ApplicationPackageManager: load=net.minetest.minetest, bg=144-144, dr=336-336, forDefault=true, density=0
2018-12-21 20:30:37.489 28942-29121/? I/GameTools: GameToolsIntentService : PAUSED 1, net.minetest.minetest
2018-12-21 20:30:37.504 4137-25848/? I/ApplicationPackageManager: load=net.minetest.minetest-contain, bg=284-284, dr=216-216
2018-12-21 20:30:41.338 28892-29188/? V/LauncherApps: Returning activity for profile UserHandle{0} : ComponentInfo{com.rubenwardy.minetestmodmanager/com.rubenwardy.minetestmodmanager.views.ModListActivity}
2018-12-21 20:30:41.455 28892-29188/? V/LauncherApps: Returning activity for profile UserHandle{0} : ComponentInfo{net.minetest.minetest/net.minetest.minetest.MainActivity}
```

**Comment by stujones11** [comment]
I see no actual errors in there, only information and a few warnings. I'd guess that the device simply ran out of memory.

**Comment by rubenwardy** [comment]
Would you be able to make an Android build without screenshots please? 

Modify around builtin/mainmenu/dlg_contentstore.lua:147 to look like this:

```lua
local function get_screenshot(package)
	return defaulttexturedir .. "no_screenshot.png"
end
```

(I can't do this without the app overwriting my changes)

**Comment by rubenwardy** [comment]
> I see no actual errors in there, only information and a few warnings. I'd guess that the device simply ran out of memory.

My phone has 4GB of Memory, yet CDB only uses 67MB on Linux. So there's something interesting happening here

**Comment by rubenwardy** [comment]
It may be a lot more useful to have a build without the asset copier, as I'd then be able to modify it without having to setup an Android build env

**Comment by stujones11** [comment]
APK with no cdb screenshots as requested: [Minetest-cdb-screenshot.apk](https://www.dropbox.com/s/plg6ionusl3d9st/Minetest-cdb-screenshot.apk?dl=0)

**Comment by Fixer-007** [comment]
Will still post screenshot of weird looking progress bar: https://i.imgur.com/ayCX8GH.png

**Comment by nerzhul** [comment]
When all issues are fixed, tell me which commits to backport to generate a prerelease of the 0.4.17.3
