### ISSUE TITLE
Inventory crash during map load

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#831]
If you sign onto a server and request your inventory too quickly, i.e. while the initial, surrounding map is still downloading, the client will crash.  If you wait until the map around you finishes loading, it'll usually be fine, but this can take upwards of a full minute on a slow server.

To test this, you'll need Unified Inventory (part of the Technic modpack), a high resolution texture pack on the client, and "preload item visuals" to be un-checked/disabled on your client, to trigger this issue (because all of these force the client to take a while to fully render the first inventory page).  It may be necessary to use separate server and client processes running on the same machine.

Crash output + debug-mode backtrace:

```
In thread 7fffdca49700:
/home/vanessa/Minetest-related/minetest_core/src/tile.cpp:537: virtual irr::u32 TextureSource::getTextureId(const string&): Assertion 'result.key == name' failed.
Debug stacks:
DEBUG STACK FOR THREAD 7fffdca49700:
#0  virtual void* MeshUpdateThread::Thread()
DEBUG STACK FOR THREAD 7ffff7eaa780:
#0  int main(int, char**)
#1  void Client::step(float)
#2  virtual void ClientEnvironment::step(float)
(Leftover data: #3  void Client::Receive())
(Leftover data: #4  void Client::ProcessData(irr::u8*, irr::u32, irr::u16))
(Leftover data: #5  void MeshUpdateQueue::addBlock(v3s16, MeshMakeData*, bool, bool))

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdca49700 (LWP 6594)]
0x00007ffff4a191e5 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff4a191e5 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 6561
        selftid = 6594
#1  0x00007ffff4a1c398 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0xada030, sa_sigaction = 0xada030}, sa_mask = {__val = {11218787, 
              15588480, 140737351945653, 4294967301, 0, 537, 140737297427688, 15485120, 15588480, 15485120, 
              140737351971317, 0, 4222418956, 140737301227160, 1, 1}}, sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000006790ba in assert_fail (assertion=assertion@entry=0xab2f63 "result.key == name", 
    file=file@entry=0xada030 "/home/vanessa/Minetest-related/minetest_core/src/tile.cpp", line=line@entry=537, 
    function=function@entry=0xada700 <TextureSource::getTextureId(std::string const&)::__PRETTY_FUNCTION__> "virtual irr::u32 TextureSource::getTextureId(const string&)") at /home/vanessa/Minetest-related/minetest_core/src/debug.cpp:79
No locals.
#3  0x00000000007b9bd0 in TextureSource::getTextureId (this=<optimized out>, name=...)
    at /home/vanessa/Minetest-related/minetest_core/src/tile.cpp:537
        result = {key = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffd001b1c8 "moreblocks_empty_bookshelf_normal.png"}}, item = 2101, 
          callers = {<std::_List_base<CallerInfo<unsigned char, unsigned char>, std::allocator<CallerInfo<unsigned char, unsigned char> > >> = {
              _M_impl = {<std::allocator<std::_List_node<CallerInfo<unsigned char, unsigned char> > >> = {<__gnu_cxx::new_all---Type <return> to continue, or q <return> to quit---
ocator<std::_List_node<CallerInfo<unsigned char, unsigned char> > >> = {<No data fields>}, <No data fields>}, _M_node = {
                  _M_next = 0x7fffd00e01d0, _M_prev = 0x7fffd00e01d0}}}, <No data fields>}}
        result_queue = {<MutexedQueue<GetResult<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned char, unsigned char> >> = {m_mutex = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                  __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
                __size = '\000' <repeats 39 times>, __align = 0}, initialized = true}, 
            m_list = {<std::_List_base<GetResult<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned char, unsigned char>, std::allocator<GetResult<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned char, unsigned char> > >> = {
                _M_impl = {<std::allocator<std::_List_node<GetResult<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned char, unsigned char> > >> = {<__gnu_cxx::new_allocator<std::_List_node<GetResult<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned char, unsigned char> > >> = {<No data fields>}, <No data fields>}, _M_node = {_M_next = 0x7fffdca48650, 
                    _M_prev = 0x7fffdca48650}}}, <No data fields>}}, <No data fields>}
        __PRETTY_FUNCTION__ = "virtual irr::u32 TextureSource::getTextureId(const string&)"
#4  0x00000000007b7e9a in TextureSource::getTexture (this=0x13bb4c0, name=..., id=0x0)
    at /home/vanessa/Minetest-related/minetest_core/src/tile.cpp:767
        actual_id = <optimized out>
#5  0x0000000000765fdb in MapBlockMesh::MapBlockMesh (this=0x7fffd00044a0, data=0x65a49410)
    at /home/vanessa/Minetest-related/minetest_core/src/mapblock_mesh.cpp:1183
        i = <optimized out>
        tsrc = 0x13bb4c0
        fname_base = {static npos = <optimized out>, 
---Type <return> to continue, or q <return> to quit---
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffd0012dd8 "junglegrass_shortest_normal.png"}}
        normal_ext = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffd000e298 "_normal.png"}}
        pos = 0
        fname_normal = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffd0081fb8 "junglegrass_shortest_normal.png"}}
        smat1 = 24
        smat2 = 25
        smat3 = 26
        material = {TextureLayer = {{Texture = 0x499909e0, TextureWrapU = 0 '\000', TextureWrapV = 0 '\000', 
              BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 0 '\000', LODBias = 0 '\000', 
              MatrixAllocator = {
                _vptr.irrAllocator = 0xacd670 <vtable for irr::core::irrAllocator<irr::core::CMatrix4<float> >+16>}, 
              TextureMatrix = 0x0}, {Texture = 0x0, TextureWrapU = 0 '\000', TextureWrapV = 0 '\000', 
              BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 0 '\000', LODBias = 0 '\000', 
              MatrixAllocator = {
                _vptr.irrAllocator = 0xacd670 <vtable for irr::core::irrAllocator<irr::core::CMatrix4<float> >+16>}, 
              TextureMatrix = 0x0}, {Texture = 0x0, TextureWrapU = 0 '\000', TextureWrapV = 0 '\000', 
              BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 0 '\000', LODBias = 0 '\000', 
              MatrixAllocator = {
---Type <return> to continue, or q <return> to quit---
                _vptr.irrAllocator = 0xacd670 <vtable for irr::core::irrAllocator<irr::core::CMatrix4<float> >+16>}, 
              TextureMatrix = 0x0}, {Texture = 0x0, TextureWrapU = 0 '\000', TextureWrapV = 0 '\000', 
              BilinearFilter = false, TrilinearFilter = false, AnisotropicFilter = 0 '\000', LODBias = 0 '\000', 
              MatrixAllocator = {
                _vptr.irrAllocator = 0xacd670 <vtable for irr::core::irrAllocator<irr::core::CMatrix4<float> >+16>}, 
              TextureMatrix = 0x0}}, MaterialType = irr::video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF, AmbientColor = {
            color = 4294967295}, DiffuseColor = {color = 4294967295}, EmissiveColor = {color = 0}, SpecularColor = {
            color = 4294967295}, Shininess = 0, MaterialTypeParam = 0, MaterialTypeParam2 = 0, Thickness = 1, 
          ZBuffer = 1 '\001', AntiAliasing = 1 '\001', ColorMask = 15 '\017', ColorMaterial = 1 '\001', Wireframe = false, 
          PointCloud = false, GouraudShading = true, Lighting = false, ZWriteEnable = true, BackfaceCulling = true, 
          FrontfaceCulling = false, FogEnable = true, NormalizeNormals = false}
        buf = <optimized out>
        i = 18
        fastfaces_new = {<std::_Vector_base<FastFace, std::allocator<FastFace> >> = {
            _M_impl = {<std::allocator<FastFace>> = {<__gnu_cxx::new_allocator<FastFace>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fffd002e6d0, _M_finish = 0x7fffd0047db0, _M_end_of_storage = 0x7fffd00586d0}}, <No data fields>}
        collector = {prebuffers = {<std::_Vector_base<PreMeshBuffer, std::allocator<PreMeshBuffer> >> = {
              _M_impl = {<std::allocator<PreMeshBuffer>> = {<__gnu_cxx::new_allocator<PreMeshBuffer>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fffd0009300, _M_finish = 0x7fffd000a6b0, 
                _M_end_of_storage = 0x7fffd000b700}}, <No data fields>}}
        enable_bumpmapping = true
        enable_shaders = true
        shadermat1 = 24
---Type <return> to continue, or q <return> to quit---
        shadermat3 = 26
        bumpmaps2 = 28
        shadermat2 = 25
        bumpmaps1 = 27
#6  0x00000000007acbbc in MeshUpdateThread::Thread (this=0x7fffffffad90)
    at /home/vanessa/Minetest-related/minetest_core/src/client.cpp:198
        q = 0x172bfe0
        sp = {m_profiler = 0xec5820 <main_profiler>, m_name = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fffd0004448 "Client: Mesh making"}}, m_timer = 0x7fffd0004470, m_type = SPT_ADD}
        mesh_new = <optimized out>
        r = <optimized out>
        __debug_stacker = {m_stack = 0x7fffd0000940, m_overflowed = false}
        __PRETTY_FUNCTION__ = "virtual void* MeshUpdateThread::Thread()"
#7  0x0000000000aa22d3 in JThread::TheThread (param=0x7fffffffad90)
    at /home/vanessa/Minetest-related/minetest_core/src/jthread/pthread/jthread.cpp:171
        jthread = 0x7fffffffad90
        ret = <optimized out>
#8  0x00007ffff5e2be0e in start_thread (arg=0x7fffdca49700) at pthread_create.c:311
        __res = <optimized out>
        pd = 0x7fffdca49700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736895162112, -1558721168852921016, 1, 140737488331264, 4096, 
---Type <return> to continue, or q <return> to quit---
                140736895162112, 1558797511374918984, 1558707951018825032}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#9  0x00007ffff4acc93d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
No locals.
```

**Comment by nerzhul** [comment]
I close the issue. The bug isn't present anymore
