### ISSUE TITLE
Deadlock - Server env?

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8666]
## To reproduce

Use one client to host a server from the GUI. Try to connect to that client from another client. Witness server freeze (ie: no packets received on either client). Attempting to shutdown never finishes.

## Info

```
#0  0x00007ffff66197bc in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt full
#0  0x00007ffff66197bc in __lll_lock_wait () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00007ffff6612d68 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
No symbol table info available.
#2  0x0000555555be28a8 in Server::SendBlock(unsigned short, irr::core::vector3d<short> const&) ()
No symbol table info available.
#3  0x0000555555aeaffb in PlayerSAO::setPos(irr::core::vector3d<float> const&) ()
No symbol table info available.
#4  0x0000555555a02165 in ObjectRef::l_set_pos(lua_State*) ()
No symbol table info available.
#5  0x00005555559a8ef6 in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
No symbol table info available.
#6  0x00007ffff66d196c in ?? () from /usr/lib/libluajit-5.1.so.2
No symbol table info available.
#7  0x00007ffff671797c in lua_pcall () from /usr/lib/libluajit-5.1.so.2
No symbol table info available.
#8  0x00005555559aea96 in ScriptApiBase::runCallbacksRaw(int, RunCallbacksMode, char const*) ()
No symbol table info available.
#9  0x00005555559bcda1 in ScriptApiPlayer::on_newplayer(ServerActiveObject*) ()
No symbol table info available.
#10 0x0000555555be25b3 in Server::emergePlayer(char const*, unsigned short, unsigned short) ()
No symbol table info available.
#11 0x0000555555bed806 in Server::StageTwoClientInit(unsigned short) ()
No symbol table info available.
#12 0x0000555555981398 in Server::handleCommand_ClientReady(NetworkPacket*) ()
No symbol table info available.
#13 0x0000555555bd8ff9 in Server::ProcessData(NetworkPacket*) ()
No symbol table info available.
#14 0x0000555555bd91b3 in Server::Receive() ()
No symbol table info available.
#15 0x0000555555bf219a in ServerThread::run() ()
```

```
  Id   Target Id                                           Frame 
* 1    Thread 0x7ffff500e940 (LWP 23937) "minetest"        0x00007ffff66197bc in __lll_lock_wait () from /usr/lib/libpthread.so.0
  4    Thread 0x7ffff494b700 (LWP 23944) "threaded-ml"     0x00007ffff5e03667 in poll ()
   from /usr/lib/libc.so.6
  5    Thread 0x7ffff3466700 (LWP 23945) "minetest"        0x00007ffff6ede6d2 in ?? ()
   from /usr/lib/libopenal.so.1
  6    Thread 0x7ffff2a3e700 (LWP 23946) "minetest"        0x00007ffff6618d16 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  7    Thread 0x7ffff137b700 (LWP 23947) "minetes:disk$0"  0x00007ffff6616415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  12   Thread 0x7fffd1737700 (LWP 23957) "ConnectionSend"  0x00007ffff6618f42 in do_futex_wait () from /usr/lib/libpthread.so.0
  13   Thread 0x7fffd1f38700 (LWP 23958) "ConnectionRecei" 0x00007ffff5e05e5b in select ()
   from /usr/lib/libc.so.6
  14   Thread 0x7fffd2739700 (LWP 23959) "Server"          0x00007ffff66197bc in __lll_lock_wait () from /usr/lib/libpthread.so.0
  19   Thread 0x7fffb6ffd700 (LWP 23964) "Emerge-0"        0x00007ffff6616415 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
```

**Comment by rubenwardy** [comment]
I'm no longer able to reproduce this, and I made the mistake of closing the problem. I was able to consistently reproduce this before

**Comment by paramat** [comment]
Can't reproduce using a server and client on one machine.

**Comment by Zughy** [comment]
No further info in a year and a half. Possible close?
