### ISSUE TITLE
Segfault when exiting from world to menu when driving a MTG boat

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9033]
In singleplayer, attach to a boat, exit to menu.
I'm on commit b49dfa92ce3ef37b1b73698906c64191fb47e226
I don't consider it a blocker though.
```
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x00005555556c9ee7 in GenericCAO::setAttachment(int, std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&, irr::core::vector3d<float>,
irr::core::vector3d<float>) ()
(gdb) bt full
#0  0x00005555556c9ee7 in GenericCAO::setAttachment(int, std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > const&, irr::core::vector3d<float>,
irr::core::vector3d<float>) ()
No symbol table info available.
#1  0x00005555556ca5f9 in GenericCAO::clearParentAttachment() ()
No symbol table info available.
#2  0x00005555556c933e in GenericCAO::removeFromScene(bool) ()
No symbol table info available.
#3  0x00005555556c9f3b in GenericCAO::~GenericCAO() ()
No symbol table info available.
#4  0x00005555556ca229 in GenericCAO::~GenericCAO() ()
No symbol table info available.
#5  0x000055555567facf in client::ActiveObjectMgr::clear() ()
No symbol table info available.
#6  0x000055555569c9c5 in ClientEnvironment::~ClientEnvironment() ()
No symbol table info available.
#7  0x0000555555694a1f in Client::~Client() ()
No symbol table info available.
#8  0x0000555555694d09 in Client::~Client() ()
No symbol table info available.
#9  0x00005555556fd32c in Game::~Game() ()
No symbol table info available.
#10 0x0000555555705276 in the_game(bool*, bool, InputHandler*,
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat
```

**Comment by paramat** [comment]
Suspect 4aa9a669cb184b77213e8df82eb20eda5aad9004 #8701 
@SmallJoker

**Comment by SmallJoker** [comment]
Rough bisect showed the same commit for me. Carts and other entities are affected too.

**Comment by SmallJoker** [comment]
cbcb9e0b1
