### ISSUE TITLE
GUI: Segfault in destructor

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#9176]
Observed in current master (5.2.0-dev). Noticed the segfault last week but caught it in gdb this time.

1) Join singleplayer world
2) ESC pause menu
3) `Exit to OS` button

EDIT: Also happens in mainmenu when quitting from any tab.

```C++
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x00007ffff765c1be in irr::gui::CGUIEnvironment::~CGUIEnvironment() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
(gdb) bt
#0  0x00007ffff765c1be in irr::gui::CGUIEnvironment::~CGUIEnvironment() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#1  0x00007ffff765c4e9 in irr::gui::CGUIEnvironment::~CGUIEnvironment() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#2  0x00007ffff74bb5a6 in irr::scene::CSceneManager::~CSceneManager() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#3  0x00007ffff74bb609 in irr::scene::CSceneManager::~CSceneManager() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#4  0x00007ffff7617c7e in irr::CIrrDeviceLinux::~CIrrDeviceLinux() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#5  0x00007ffff7617ce9 in irr::CIrrDeviceLinux::~CIrrDeviceLinux() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#6  0x0000555555775860 in RenderingEngine::~RenderingEngine() ()
#7  0x00005555556a6503 in ClientLauncher::~ClientLauncher() ()
#8  0x0000555555681b18 in main ()
```

The problem can be one of those:
1) guiFormSpecMenu in general
2) StaticText
3) Button
4) Textarea (without scrollbar)
5) Background (color only)

**Comment by SmallJoker** [comment]
Seems related:
```C++
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xffffffffffffffff) at malloc.c:3103
3103	malloc.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI___libc_free (mem=0xffffffffffffffff) at malloc.c:3103
#1  0x00007ffff48f5fb9 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#2  0x00007ffff057bc38 in ?? () from /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.340.107
#3  0x00007ffff08a122d in ?? () from /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.340.107
#4  0x00007ffff055fa78 in ?? () from /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.340.107
#5  0x00007ffff772efc4 in irr::video::COpenGLDriver::deleteHardwareBuffer(irr::video::CNullDriver::SHWBufferLink*) () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#6  0x00007ffff771e197 in irr::video::CNullDriver::removeAllHardwareBuffers() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#7  0x00007ffff76be009 in irr::scene::CSceneManager::~CSceneManager() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#8  0x00007ffff76be609 in irr::scene::CSceneManager::~CSceneManager() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#9  0x0000555555bb7998 in irr::IReferenceCounted::drop (this=0x5555590c07a8)
    at /usr/include/irrlicht/IReferenceCounted.h:124
#10 0x0000555555bb3d2b in Camera::~Camera (this=0x55555ec2ed70, __in_chrg=<optimized out>)
    at PATH/src/client/camera.cpp:83
#11 0x0000555555c42219 in Game::~Game (this=0x7fffffffd460, __in_chrg=<optimized out>)
    at PATH/src/client/game.cpp:967
#12 0x0000555555c566cd in the_game (kill=0x5555566c8920 <porting::g_killed>, random_input=false, 
    input=0x555556aa9220, map_dir="PATH/bin/../worlds/mtg", 
    playername="singleplayer", password="", address="", port=61146, error_message="", 
    chat_backend=..., reconnect_requested=0x7fffffffd79c, gamespec=..., 
    simple_singleplayer_mode=true) at PATH/src/client/game.cpp:4182
#13 0x0000555555bf3f8b in ClientLauncher::run (this=0x7fffffffdd10, game_params=..., cmd_args=...)
```

**Comment by Zughy** [comment]
I've just tried to reproduce it (5.4.0-dev) with gdb, no segmentation fault. Linux Mint

```
2020-12-16 23:28:07: ACTION[Main]: Server: Shutting down
[Thread 0x7fffbd7fa700 (LWP 18340) terminado]
[Thread 0x7fffce383700 (LWP 18335) terminado]
[Thread 0x7fffcd381700 (LWP 18333) terminado]
[Thread 0x7fffcdb82700 (LWP 18334) terminado]
[Thread 0x7fffd6eaf700 (LWP 18323) terminado]
[Thread 0x7fffe76b0700 (LWP 18322) terminado]
[Inferior 1 (process 18316) exited normally]
```

**Comment by SmallJoker** [comment]
Will re-open as soon this occurs again.
