### ISSUE TITLE
Memory corruption (recent)

### ISSUE THREAD

**Issue by IFRFSX** [minetest/minetest#9338]
2020-01-24 21:14:44: ACTION[Server]: singleplayer granted (server, shout, fly, password, creative, bring, kick, teleport, ban, noclip, home, privs, fast, basic_privs, debug, give, protection_bypass, rollback, settime, interact) privileges to singleplayer
^[free(): invalid next size (normal)
Aborted (core dumped)

**Comment by SmallJoker** [comment]
master debug build, a1da9ca
```C++
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x00007ffff7634ad5 in irr::scene::CAnimatedMeshSceneNode::getMeshForCurrentFrame() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
(gdb) bt
#0  0x00007ffff7634ad5 in irr::scene::CAnimatedMeshSceneNode::getMeshForCurrentFrame() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#1  0x00007ffff7634d04 in irr::scene::CAnimatedMeshSceneNode::OnAnimate(unsigned int) ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#2  0x00007ffff7627cd4 in irr::scene::ISceneNode::OnAnimate(unsigned int) ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#3  0x00007ffff76be96d in irr::scene::CSceneManager::drawAll() ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#4  0x0000555555cc0e51 in RenderingCore::draw3D (this=0x55555f003b30)
    at PATH/src/client/render/core.cpp:75
#5  0x0000555555cc30e2 in RenderingCorePlain::drawAll (this=0x55555f003b30)
    at PATH/src/client/render/plain.cpp:72
#6  0x0000555555cc0e0d in RenderingCore::draw (this=0x55555f003b30, _skycolor=..., _show_hud=true, 
    _show_minimap=false, _draw_wield_tool=true, _draw_crosshair=true)
    at PATH/src/client/render/core.cpp:70
#7  0x0000555555cc6545 in RenderingEngine::_draw_scene (this=0x55555677cbd0, skycolor=..., 
    show_hud=true, show_minimap=false, draw_wield_tool=true, draw_crosshair=true)
    at PATH/src/client/renderingengine.cpp:615
#8  0x0000555555c57957 in RenderingEngine::draw_scene (skycolor=..., show_hud=true, 
    show_minimap=false, draw_wield_tool=true, draw_crosshair=true)
    at PATH/src/client/renderingengine.h:122
#9  0x0000555555c52cad in Game::updateFrame (this=0x7fffffffd480, graph=0x7fffffffd320, 
    stats=0x7fffffffd2e0, dtime=0.0170000009, cam=...)
    at PATH/src/client/game.cpp:3837
#10 0x0000555555c43317 in Game::run (this=0x7fffffffd480)
    at PATH/src/client/game.cpp:1134
#11 0x0000555555c566a0 in the_game (kill=0x5555566c8920 <porting::g_killed>, random_input=false, 
    input=0x555556aa8f90, map_dir="PATH/bin/../worlds/mtg", 
    playername="singleplayer", password="", address="", port=53077, error_message="", 
    chat_backend=..., reconnect_requested=0x7fffffffd7bc, gamespec=..., 
    simple_singleplayer_mode=true) at PATH/src/client/game.cpp:4196
#12 0x0000555555bf3f8b in ClientLauncher::run (this=0x7fffffffdd30, game_params=..., cmd_args=...)
    at PATH/src/client/clientlauncher.cpp:259
#13 0x0000555556038ab3 in main (argc=1, argv=0x7fffffffe0a8)
    at PATH/src/main.cpp:218
```

**Comment by SmallJoker** [comment]
9cb3219f3
